.PHONY: all get-api update-version create-bindings

all: get-api update-version create-bindings

get-api:
	cd get-api && ./get-api.sh

update-version:
	cd update-version && ./update-version.sh

create-bindings:
	cd create-bindings && ./create-bindings.sh
