/*
API Documentation

Source of truth and network automation platform

API version: 2.3.2 (2.3)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// PatchedWritablePowerOutletRequestFeedLeg - Phase (for three-phase feeds)
type PatchedWritablePowerOutletRequestFeedLeg struct {
	BlankEnum *BlankEnum
	FeedLegEnum *FeedLegEnum
}

// BlankEnumAsPatchedWritablePowerOutletRequestFeedLeg is a convenience function that returns BlankEnum wrapped in PatchedWritablePowerOutletRequestFeedLeg
func BlankEnumAsPatchedWritablePowerOutletRequestFeedLeg(v *BlankEnum) PatchedWritablePowerOutletRequestFeedLeg {
	return PatchedWritablePowerOutletRequestFeedLeg{
		BlankEnum: v,
	}
}

// FeedLegEnumAsPatchedWritablePowerOutletRequestFeedLeg is a convenience function that returns FeedLegEnum wrapped in PatchedWritablePowerOutletRequestFeedLeg
func FeedLegEnumAsPatchedWritablePowerOutletRequestFeedLeg(v *FeedLegEnum) PatchedWritablePowerOutletRequestFeedLeg {
	return PatchedWritablePowerOutletRequestFeedLeg{
		FeedLegEnum: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PatchedWritablePowerOutletRequestFeedLeg) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into BlankEnum
	err = newStrictDecoder(data).Decode(&dst.BlankEnum)
	if err == nil {
		jsonBlankEnum, _ := json.Marshal(dst.BlankEnum)
		if string(jsonBlankEnum) == "{}" { // empty struct
			dst.BlankEnum = nil
		} else {
			if err = validator.Validate(dst.BlankEnum); err != nil {
				dst.BlankEnum = nil
			} else {
				match++
			}
		}
	} else {
		dst.BlankEnum = nil
	}

	// try to unmarshal data into FeedLegEnum
	err = newStrictDecoder(data).Decode(&dst.FeedLegEnum)
	if err == nil {
		jsonFeedLegEnum, _ := json.Marshal(dst.FeedLegEnum)
		if string(jsonFeedLegEnum) == "{}" { // empty struct
			dst.FeedLegEnum = nil
		} else {
			if err = validator.Validate(dst.FeedLegEnum); err != nil {
				dst.FeedLegEnum = nil
			} else {
				match++
			}
		}
	} else {
		dst.FeedLegEnum = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.BlankEnum = nil
		dst.FeedLegEnum = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PatchedWritablePowerOutletRequestFeedLeg)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PatchedWritablePowerOutletRequestFeedLeg)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PatchedWritablePowerOutletRequestFeedLeg) MarshalJSON() ([]byte, error) {
	if src.BlankEnum != nil {
		return json.Marshal(&src.BlankEnum)
	}

	if src.FeedLegEnum != nil {
		return json.Marshal(&src.FeedLegEnum)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PatchedWritablePowerOutletRequestFeedLeg) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.BlankEnum != nil {
		return obj.BlankEnum
	}

	if obj.FeedLegEnum != nil {
		return obj.FeedLegEnum
	}

	// all schemas are nil
	return nil
}

type NullablePatchedWritablePowerOutletRequestFeedLeg struct {
	value *PatchedWritablePowerOutletRequestFeedLeg
	isSet bool
}

func (v NullablePatchedWritablePowerOutletRequestFeedLeg) Get() *PatchedWritablePowerOutletRequestFeedLeg {
	return v.value
}

func (v *NullablePatchedWritablePowerOutletRequestFeedLeg) Set(val *PatchedWritablePowerOutletRequestFeedLeg) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedWritablePowerOutletRequestFeedLeg) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedWritablePowerOutletRequestFeedLeg) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedWritablePowerOutletRequestFeedLeg(val *PatchedWritablePowerOutletRequestFeedLeg) *NullablePatchedWritablePowerOutletRequestFeedLeg {
	return &NullablePatchedWritablePowerOutletRequestFeedLeg{value: val, isSet: true}
}

func (v NullablePatchedWritablePowerOutletRequestFeedLeg) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedWritablePowerOutletRequestFeedLeg) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


