/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
)

// checks if the PatchedDataComplianceRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedDataComplianceRequest{}

// PatchedDataComplianceRequest Serializer for DataCompliance.
type PatchedDataComplianceRequest struct {
	Id *string `json:"id,omitempty"`
	ComplianceClassName *string `json:"compliance_class_name,omitempty"`
	ObjectId *string `json:"object_id,omitempty"`
	ValidatedObjectStr *string `json:"validated_object_str,omitempty"`
	ValidatedAttribute *string `json:"validated_attribute,omitempty"`
	ValidatedAttributeValue *string `json:"validated_attribute_value,omitempty"`
	Valid *bool `json:"valid,omitempty"`
	Message *string `json:"message,omitempty"`
	ContentType *BulkWritableCableRequestStatus `json:"content_type,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Relationships *map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue `json:"relationships,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedDataComplianceRequest PatchedDataComplianceRequest

// NewPatchedDataComplianceRequest instantiates a new PatchedDataComplianceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedDataComplianceRequest() *PatchedDataComplianceRequest {
	this := PatchedDataComplianceRequest{}
	var validatedAttribute string = ""
	this.ValidatedAttribute = &validatedAttribute
	return &this
}

// NewPatchedDataComplianceRequestWithDefaults instantiates a new PatchedDataComplianceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedDataComplianceRequestWithDefaults() *PatchedDataComplianceRequest {
	this := PatchedDataComplianceRequest{}
	var validatedAttribute string = ""
	this.ValidatedAttribute = &validatedAttribute
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchedDataComplianceRequest) SetId(v string) {
	o.Id = &v
}

// GetComplianceClassName returns the ComplianceClassName field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetComplianceClassName() string {
	if o == nil || IsNil(o.ComplianceClassName) {
		var ret string
		return ret
	}
	return *o.ComplianceClassName
}

// GetComplianceClassNameOk returns a tuple with the ComplianceClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetComplianceClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.ComplianceClassName) {
		return nil, false
	}
	return o.ComplianceClassName, true
}

// HasComplianceClassName returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasComplianceClassName() bool {
	if o != nil && !IsNil(o.ComplianceClassName) {
		return true
	}

	return false
}

// SetComplianceClassName gets a reference to the given string and assigns it to the ComplianceClassName field.
func (o *PatchedDataComplianceRequest) SetComplianceClassName(v string) {
	o.ComplianceClassName = &v
}

// GetObjectId returns the ObjectId field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetObjectId() string {
	if o == nil || IsNil(o.ObjectId) {
		var ret string
		return ret
	}
	return *o.ObjectId
}

// GetObjectIdOk returns a tuple with the ObjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetObjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectId) {
		return nil, false
	}
	return o.ObjectId, true
}

// HasObjectId returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasObjectId() bool {
	if o != nil && !IsNil(o.ObjectId) {
		return true
	}

	return false
}

// SetObjectId gets a reference to the given string and assigns it to the ObjectId field.
func (o *PatchedDataComplianceRequest) SetObjectId(v string) {
	o.ObjectId = &v
}

// GetValidatedObjectStr returns the ValidatedObjectStr field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetValidatedObjectStr() string {
	if o == nil || IsNil(o.ValidatedObjectStr) {
		var ret string
		return ret
	}
	return *o.ValidatedObjectStr
}

// GetValidatedObjectStrOk returns a tuple with the ValidatedObjectStr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetValidatedObjectStrOk() (*string, bool) {
	if o == nil || IsNil(o.ValidatedObjectStr) {
		return nil, false
	}
	return o.ValidatedObjectStr, true
}

// HasValidatedObjectStr returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasValidatedObjectStr() bool {
	if o != nil && !IsNil(o.ValidatedObjectStr) {
		return true
	}

	return false
}

// SetValidatedObjectStr gets a reference to the given string and assigns it to the ValidatedObjectStr field.
func (o *PatchedDataComplianceRequest) SetValidatedObjectStr(v string) {
	o.ValidatedObjectStr = &v
}

// GetValidatedAttribute returns the ValidatedAttribute field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetValidatedAttribute() string {
	if o == nil || IsNil(o.ValidatedAttribute) {
		var ret string
		return ret
	}
	return *o.ValidatedAttribute
}

// GetValidatedAttributeOk returns a tuple with the ValidatedAttribute field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetValidatedAttributeOk() (*string, bool) {
	if o == nil || IsNil(o.ValidatedAttribute) {
		return nil, false
	}
	return o.ValidatedAttribute, true
}

// HasValidatedAttribute returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasValidatedAttribute() bool {
	if o != nil && !IsNil(o.ValidatedAttribute) {
		return true
	}

	return false
}

// SetValidatedAttribute gets a reference to the given string and assigns it to the ValidatedAttribute field.
func (o *PatchedDataComplianceRequest) SetValidatedAttribute(v string) {
	o.ValidatedAttribute = &v
}

// GetValidatedAttributeValue returns the ValidatedAttributeValue field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetValidatedAttributeValue() string {
	if o == nil || IsNil(o.ValidatedAttributeValue) {
		var ret string
		return ret
	}
	return *o.ValidatedAttributeValue
}

// GetValidatedAttributeValueOk returns a tuple with the ValidatedAttributeValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetValidatedAttributeValueOk() (*string, bool) {
	if o == nil || IsNil(o.ValidatedAttributeValue) {
		return nil, false
	}
	return o.ValidatedAttributeValue, true
}

// HasValidatedAttributeValue returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasValidatedAttributeValue() bool {
	if o != nil && !IsNil(o.ValidatedAttributeValue) {
		return true
	}

	return false
}

// SetValidatedAttributeValue gets a reference to the given string and assigns it to the ValidatedAttributeValue field.
func (o *PatchedDataComplianceRequest) SetValidatedAttributeValue(v string) {
	o.ValidatedAttributeValue = &v
}

// GetValid returns the Valid field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetValid() bool {
	if o == nil || IsNil(o.Valid) {
		var ret bool
		return ret
	}
	return *o.Valid
}

// GetValidOk returns a tuple with the Valid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetValidOk() (*bool, bool) {
	if o == nil || IsNil(o.Valid) {
		return nil, false
	}
	return o.Valid, true
}

// HasValid returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasValid() bool {
	if o != nil && !IsNil(o.Valid) {
		return true
	}

	return false
}

// SetValid gets a reference to the given bool and assigns it to the Valid field.
func (o *PatchedDataComplianceRequest) SetValid(v bool) {
	o.Valid = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PatchedDataComplianceRequest) SetMessage(v string) {
	o.Message = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetContentType() BulkWritableCableRequestStatus {
	if o == nil || IsNil(o.ContentType) {
		var ret BulkWritableCableRequestStatus
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetContentTypeOk() (*BulkWritableCableRequestStatus, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given BulkWritableCableRequestStatus and assigns it to the ContentType field.
func (o *PatchedDataComplianceRequest) SetContentType(v BulkWritableCableRequestStatus) {
	o.ContentType = &v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedDataComplianceRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *PatchedDataComplianceRequest) GetRelationships() map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue {
	if o == nil || IsNil(o.Relationships) {
		var ret map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedDataComplianceRequest) GetRelationshipsOk() (*map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *PatchedDataComplianceRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue and assigns it to the Relationships field.
func (o *PatchedDataComplianceRequest) SetRelationships(v map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue) {
	o.Relationships = &v
}

func (o PatchedDataComplianceRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedDataComplianceRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ComplianceClassName) {
		toSerialize["compliance_class_name"] = o.ComplianceClassName
	}
	if !IsNil(o.ObjectId) {
		toSerialize["object_id"] = o.ObjectId
	}
	if !IsNil(o.ValidatedObjectStr) {
		toSerialize["validated_object_str"] = o.ValidatedObjectStr
	}
	if !IsNil(o.ValidatedAttribute) {
		toSerialize["validated_attribute"] = o.ValidatedAttribute
	}
	if !IsNil(o.ValidatedAttributeValue) {
		toSerialize["validated_attribute_value"] = o.ValidatedAttributeValue
	}
	if !IsNil(o.Valid) {
		toSerialize["valid"] = o.Valid
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedDataComplianceRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedDataComplianceRequest := _PatchedDataComplianceRequest{}

	err = json.Unmarshal(data, &varPatchedDataComplianceRequest)

	if err != nil {
		return err
	}

	*o = PatchedDataComplianceRequest(varPatchedDataComplianceRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "compliance_class_name")
		delete(additionalProperties, "object_id")
		delete(additionalProperties, "validated_object_str")
		delete(additionalProperties, "validated_attribute")
		delete(additionalProperties, "validated_attribute_value")
		delete(additionalProperties, "valid")
		delete(additionalProperties, "message")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "relationships")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedDataComplianceRequest struct {
	value *PatchedDataComplianceRequest
	isSet bool
}

func (v NullablePatchedDataComplianceRequest) Get() *PatchedDataComplianceRequest {
	return v.value
}

func (v *NullablePatchedDataComplianceRequest) Set(val *PatchedDataComplianceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedDataComplianceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedDataComplianceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedDataComplianceRequest(val *PatchedDataComplianceRequest) *NullablePatchedDataComplianceRequest {
	return &NullablePatchedDataComplianceRequest{value: val, isSet: true}
}

func (v NullablePatchedDataComplianceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedDataComplianceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


