/*
API Documentation

Source of truth and network automation platform

API version: 2.4.21 (2.4)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// checks if the NestedRadioProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NestedRadioProfile{}

// NestedRadioProfile Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
type NestedRadioProfile struct {
	Id *string `json:"id,omitempty"`
	ObjectType string `json:"object_type" validate:"regexp=^[a-z][a-z0-9_]+\\\\.[a-z][a-z0-9_]+$"`
	Url string `json:"url"`
	AdditionalProperties map[string]interface{}
}

type _NestedRadioProfile NestedRadioProfile

// NewNestedRadioProfile instantiates a new NestedRadioProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNestedRadioProfile(objectType string, url string) *NestedRadioProfile {
	this := NestedRadioProfile{}
	this.ObjectType = objectType
	this.Url = url
	return &this
}

// NewNestedRadioProfileWithDefaults instantiates a new NestedRadioProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNestedRadioProfileWithDefaults() *NestedRadioProfile {
	this := NestedRadioProfile{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NestedRadioProfile) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NestedRadioProfile) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NestedRadioProfile) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NestedRadioProfile) SetId(v string) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value
func (o *NestedRadioProfile) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *NestedRadioProfile) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *NestedRadioProfile) SetObjectType(v string) {
	o.ObjectType = v
}

// GetUrl returns the Url field value
func (o *NestedRadioProfile) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *NestedRadioProfile) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *NestedRadioProfile) SetUrl(v string) {
	o.Url = v
}

func (o NestedRadioProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NestedRadioProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["object_type"] = o.ObjectType
	toSerialize["url"] = o.Url

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NestedRadioProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_type",
		"url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNestedRadioProfile := _NestedRadioProfile{}

	err = json.Unmarshal(data, &varNestedRadioProfile)

	if err != nil {
		return err
	}

	*o = NestedRadioProfile(varNestedRadioProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNestedRadioProfile struct {
	value *NestedRadioProfile
	isSet bool
}

func (v NullableNestedRadioProfile) Get() *NestedRadioProfile {
	return v.value
}

func (v *NullableNestedRadioProfile) Set(val *NestedRadioProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableNestedRadioProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableNestedRadioProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNestedRadioProfile(val *NestedRadioProfile) *NullableNestedRadioProfile {
	return &NullableNestedRadioProfile{value: val, isSet: true}
}

func (v NullableNestedRadioProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNestedRadioProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


