/*
API Documentation

Source of truth and network automation platform

API version: 2.3.2 (2.3)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
)

// checks if the BulkWritableServiceRequestDevice type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkWritableServiceRequestDevice{}

// BulkWritableServiceRequestDevice Required if no virtual_machine is specified
type BulkWritableServiceRequestDevice struct {
	Id *BulkWritableCableRequestStatusId `json:"id,omitempty"`
	ObjectType *string `json:"object_type,omitempty" validate:"regexp=^[a-z][a-z0-9_]+\\\\.[a-z][a-z0-9_]+$"`
	Url *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkWritableServiceRequestDevice BulkWritableServiceRequestDevice

// NewBulkWritableServiceRequestDevice instantiates a new BulkWritableServiceRequestDevice object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkWritableServiceRequestDevice() *BulkWritableServiceRequestDevice {
	this := BulkWritableServiceRequestDevice{}
	return &this
}

// NewBulkWritableServiceRequestDeviceWithDefaults instantiates a new BulkWritableServiceRequestDevice object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkWritableServiceRequestDeviceWithDefaults() *BulkWritableServiceRequestDevice {
	this := BulkWritableServiceRequestDevice{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BulkWritableServiceRequestDevice) GetId() BulkWritableCableRequestStatusId {
	if o == nil || IsNil(o.Id) {
		var ret BulkWritableCableRequestStatusId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableServiceRequestDevice) GetIdOk() (*BulkWritableCableRequestStatusId, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BulkWritableServiceRequestDevice) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given BulkWritableCableRequestStatusId and assigns it to the Id field.
func (o *BulkWritableServiceRequestDevice) SetId(v BulkWritableCableRequestStatusId) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *BulkWritableServiceRequestDevice) GetObjectType() string {
	if o == nil || IsNil(o.ObjectType) {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableServiceRequestDevice) GetObjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectType) {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *BulkWritableServiceRequestDevice) HasObjectType() bool {
	if o != nil && !IsNil(o.ObjectType) {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *BulkWritableServiceRequestDevice) SetObjectType(v string) {
	o.ObjectType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BulkWritableServiceRequestDevice) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableServiceRequestDevice) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BulkWritableServiceRequestDevice) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BulkWritableServiceRequestDevice) SetUrl(v string) {
	o.Url = &v
}

func (o BulkWritableServiceRequestDevice) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkWritableServiceRequestDevice) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ObjectType) {
		toSerialize["object_type"] = o.ObjectType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkWritableServiceRequestDevice) UnmarshalJSON(data []byte) (err error) {
	varBulkWritableServiceRequestDevice := _BulkWritableServiceRequestDevice{}

	err = json.Unmarshal(data, &varBulkWritableServiceRequestDevice)

	if err != nil {
		return err
	}

	*o = BulkWritableServiceRequestDevice(varBulkWritableServiceRequestDevice)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkWritableServiceRequestDevice struct {
	value *BulkWritableServiceRequestDevice
	isSet bool
}

func (v NullableBulkWritableServiceRequestDevice) Get() *BulkWritableServiceRequestDevice {
	return v.value
}

func (v *NullableBulkWritableServiceRequestDevice) Set(val *BulkWritableServiceRequestDevice) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWritableServiceRequestDevice) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWritableServiceRequestDevice) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWritableServiceRequestDevice(val *BulkWritableServiceRequestDevice) *NullableBulkWritableServiceRequestDevice {
	return &NullableBulkWritableServiceRequestDevice{value: val, isSet: true}
}

func (v NullableBulkWritableServiceRequestDevice) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWritableServiceRequestDevice) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


