/*
 * API Documentation
 *
 * Source of truth and network automation platform
 *
 * API version: 2.2.5 (2.2)
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package nautobot

type FaceEnum string

// List of FaceEnum
const (
	FRONT_FaceEnum FaceEnum = "front"
	REAR_FaceEnum FaceEnum = "rear"
)
