/*
API Documentation

Source of truth and network automation platform

API version: 2.3.2 (2.3)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// checks if the NoteInputRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NoteInputRequest{}

// NoteInputRequest struct for NoteInputRequest
type NoteInputRequest struct {
	Note string `json:"note"`
	AdditionalProperties map[string]interface{}
}

type _NoteInputRequest NoteInputRequest

// NewNoteInputRequest instantiates a new NoteInputRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNoteInputRequest(note string) *NoteInputRequest {
	this := NoteInputRequest{}
	this.Note = note
	return &this
}

// NewNoteInputRequestWithDefaults instantiates a new NoteInputRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNoteInputRequestWithDefaults() *NoteInputRequest {
	this := NoteInputRequest{}
	return &this
}

// GetNote returns the Note field value
func (o *NoteInputRequest) GetNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Note
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
func (o *NoteInputRequest) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Note, true
}

// SetNote sets field value
func (o *NoteInputRequest) SetNote(v string) {
	o.Note = v
}

func (o NoteInputRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NoteInputRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["note"] = o.Note

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *NoteInputRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"note",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNoteInputRequest := _NoteInputRequest{}

	err = json.Unmarshal(data, &varNoteInputRequest)

	if err != nil {
		return err
	}

	*o = NoteInputRequest(varNoteInputRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "note")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableNoteInputRequest struct {
	value *NoteInputRequest
	isSet bool
}

func (v NullableNoteInputRequest) Get() *NoteInputRequest {
	return v.value
}

func (v *NullableNoteInputRequest) Set(val *NoteInputRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableNoteInputRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableNoteInputRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNoteInputRequest(val *NoteInputRequest) *NullableNoteInputRequest {
	return &NullableNoteInputRequest{value: val, isSet: true}
}

func (v NullableNoteInputRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNoteInputRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


