/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// VpnVpnTunnelsListEncapsulationParameterInner the model 'VpnVpnTunnelsListEncapsulationParameterInner'
type VpnVpnTunnelsListEncapsulationParameterInner string

// List of vpn_vpn_tunnels_list_encapsulation_parameter_inner
const (
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_EO_IP VpnVpnTunnelsListEncapsulationParameterInner = "EoIP"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_GRE VpnVpnTunnelsListEncapsulationParameterInner = "GRE"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_IP_IN_IP VpnVpnTunnelsListEncapsulationParameterInner = "IP-in-IP"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_I_PSEC_TRANSPORT VpnVpnTunnelsListEncapsulationParameterInner = "IPsec-Transport"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_I_PSEC_TUNNEL VpnVpnTunnelsListEncapsulationParameterInner = "IPsec-Tunnel"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_L2_TP VpnVpnTunnelsListEncapsulationParameterInner = "L2TP"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_OPEN_VPN VpnVpnTunnelsListEncapsulationParameterInner = "OpenVPN"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_PPTP VpnVpnTunnelsListEncapsulationParameterInner = "PPTP"
	VPNVPNTUNNELSLISTENCAPSULATIONPARAMETERINNER_WIRE_GUARD VpnVpnTunnelsListEncapsulationParameterInner = "WireGuard"
)

// All allowed values of VpnVpnTunnelsListEncapsulationParameterInner enum
var AllowedVpnVpnTunnelsListEncapsulationParameterInnerEnumValues = []VpnVpnTunnelsListEncapsulationParameterInner{
	"EoIP",
	"GRE",
	"IP-in-IP",
	"IPsec-Transport",
	"IPsec-Tunnel",
	"L2TP",
	"OpenVPN",
	"PPTP",
	"WireGuard",
}

func (v *VpnVpnTunnelsListEncapsulationParameterInner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := VpnVpnTunnelsListEncapsulationParameterInner(value)
	for _, existing := range AllowedVpnVpnTunnelsListEncapsulationParameterInnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid VpnVpnTunnelsListEncapsulationParameterInner", value)
}

// NewVpnVpnTunnelsListEncapsulationParameterInnerFromValue returns a pointer to a valid VpnVpnTunnelsListEncapsulationParameterInner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewVpnVpnTunnelsListEncapsulationParameterInnerFromValue(v string) (*VpnVpnTunnelsListEncapsulationParameterInner, error) {
	ev := VpnVpnTunnelsListEncapsulationParameterInner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for VpnVpnTunnelsListEncapsulationParameterInner: valid values are %v", v, AllowedVpnVpnTunnelsListEncapsulationParameterInnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v VpnVpnTunnelsListEncapsulationParameterInner) IsValid() bool {
	for _, existing := range AllowedVpnVpnTunnelsListEncapsulationParameterInnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to vpn_vpn_tunnels_list_encapsulation_parameter_inner value
func (v VpnVpnTunnelsListEncapsulationParameterInner) Ptr() *VpnVpnTunnelsListEncapsulationParameterInner {
	return &v
}

type NullableVpnVpnTunnelsListEncapsulationParameterInner struct {
	value *VpnVpnTunnelsListEncapsulationParameterInner
	isSet bool
}

func (v NullableVpnVpnTunnelsListEncapsulationParameterInner) Get() *VpnVpnTunnelsListEncapsulationParameterInner {
	return v.value
}

func (v *NullableVpnVpnTunnelsListEncapsulationParameterInner) Set(val *VpnVpnTunnelsListEncapsulationParameterInner) {
	v.value = val
	v.isSet = true
}

func (v NullableVpnVpnTunnelsListEncapsulationParameterInner) IsSet() bool {
	return v.isSet
}

func (v *NullableVpnVpnTunnelsListEncapsulationParameterInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVpnVpnTunnelsListEncapsulationParameterInner(val *VpnVpnTunnelsListEncapsulationParameterInner) *NullableVpnVpnTunnelsListEncapsulationParameterInner {
	return &NullableVpnVpnTunnelsListEncapsulationParameterInner{value: val, isSet: true}
}

func (v NullableVpnVpnTunnelsListEncapsulationParameterInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVpnVpnTunnelsListEncapsulationParameterInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

