/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// DcimPowerFeedsListPowerPathParameterInner the model 'DcimPowerFeedsListPowerPathParameterInner'
type DcimPowerFeedsListPowerPathParameterInner string

// List of dcim_power_feeds_list_power_path_parameter_inner
const (
	DCIMPOWERFEEDSLISTPOWERPATHPARAMETERINNER_A DcimPowerFeedsListPowerPathParameterInner = "a"
	DCIMPOWERFEEDSLISTPOWERPATHPARAMETERINNER_B DcimPowerFeedsListPowerPathParameterInner = "b"
)

// All allowed values of DcimPowerFeedsListPowerPathParameterInner enum
var AllowedDcimPowerFeedsListPowerPathParameterInnerEnumValues = []DcimPowerFeedsListPowerPathParameterInner{
	"a",
	"b",
}

func (v *DcimPowerFeedsListPowerPathParameterInner) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := DcimPowerFeedsListPowerPathParameterInner(value)
	for _, existing := range AllowedDcimPowerFeedsListPowerPathParameterInnerEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid DcimPowerFeedsListPowerPathParameterInner", value)
}

// NewDcimPowerFeedsListPowerPathParameterInnerFromValue returns a pointer to a valid DcimPowerFeedsListPowerPathParameterInner
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewDcimPowerFeedsListPowerPathParameterInnerFromValue(v string) (*DcimPowerFeedsListPowerPathParameterInner, error) {
	ev := DcimPowerFeedsListPowerPathParameterInner(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for DcimPowerFeedsListPowerPathParameterInner: valid values are %v", v, AllowedDcimPowerFeedsListPowerPathParameterInnerEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v DcimPowerFeedsListPowerPathParameterInner) IsValid() bool {
	for _, existing := range AllowedDcimPowerFeedsListPowerPathParameterInnerEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to dcim_power_feeds_list_power_path_parameter_inner value
func (v DcimPowerFeedsListPowerPathParameterInner) Ptr() *DcimPowerFeedsListPowerPathParameterInner {
	return &v
}

type NullableDcimPowerFeedsListPowerPathParameterInner struct {
	value *DcimPowerFeedsListPowerPathParameterInner
	isSet bool
}

func (v NullableDcimPowerFeedsListPowerPathParameterInner) Get() *DcimPowerFeedsListPowerPathParameterInner {
	return v.value
}

func (v *NullableDcimPowerFeedsListPowerPathParameterInner) Set(val *DcimPowerFeedsListPowerPathParameterInner) {
	v.value = val
	v.isSet = true
}

func (v NullableDcimPowerFeedsListPowerPathParameterInner) IsSet() bool {
	return v.isSet
}

func (v *NullableDcimPowerFeedsListPowerPathParameterInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDcimPowerFeedsListPowerPathParameterInner(val *DcimPowerFeedsListPowerPathParameterInner) *NullableDcimPowerFeedsListPowerPathParameterInner {
	return &NullableDcimPowerFeedsListPowerPathParameterInner{value: val, isSet: true}
}

func (v NullableDcimPowerFeedsListPowerPathParameterInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDcimPowerFeedsListPowerPathParameterInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

