/*
API Documentation

Source of truth and network automation platform

API version: 2.4.21 (2.4)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ModuleFamily type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ModuleFamily{}

// ModuleFamily API serializer for ModuleFamily objects.
type ModuleFamily struct {
	Id *string `json:"id,omitempty"`
	ObjectType string `json:"object_type" validate:"regexp=^[a-z][a-z0-9_]+\\.[a-z][a-z0-9_]+$"`
	// Human friendly display value
	Display string `json:"display"`
	Url string `json:"url"`
	NaturalSlug string `json:"natural_slug"`
	ModuleTypeCount *int32 `json:"module_type_count,omitempty"`
	ModuleBayCount *int32 `json:"module_bay_count,omitempty"`
	Name string `json:"name"`
	Description *string `json:"description,omitempty"`
	Created NullableTime `json:"created"`
	LastUpdated NullableTime `json:"last_updated"`
	NotesUrl string `json:"notes_url"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ModuleFamily ModuleFamily

// NewModuleFamily instantiates a new ModuleFamily object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewModuleFamily(objectType string, display string, url string, naturalSlug string, name string, created NullableTime, lastUpdated NullableTime, notesUrl string) *ModuleFamily {
	this := ModuleFamily{}
	this.ObjectType = objectType
	this.Display = display
	this.Url = url
	this.NaturalSlug = naturalSlug
	this.Name = name
	this.Created = created
	this.LastUpdated = lastUpdated
	this.NotesUrl = notesUrl
	return &this
}

// NewModuleFamilyWithDefaults instantiates a new ModuleFamily object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewModuleFamilyWithDefaults() *ModuleFamily {
	this := ModuleFamily{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ModuleFamily) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ModuleFamily) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ModuleFamily) SetId(v string) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value
func (o *ModuleFamily) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ModuleFamily) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDisplay returns the Display field value
func (o *ModuleFamily) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *ModuleFamily) SetDisplay(v string) {
	o.Display = v
}

// GetUrl returns the Url field value
func (o *ModuleFamily) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ModuleFamily) SetUrl(v string) {
	o.Url = v
}

// GetNaturalSlug returns the NaturalSlug field value
func (o *ModuleFamily) GetNaturalSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NaturalSlug
}

// GetNaturalSlugOk returns a tuple with the NaturalSlug field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetNaturalSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NaturalSlug, true
}

// SetNaturalSlug sets field value
func (o *ModuleFamily) SetNaturalSlug(v string) {
	o.NaturalSlug = v
}

// GetModuleTypeCount returns the ModuleTypeCount field value if set, zero value otherwise.
func (o *ModuleFamily) GetModuleTypeCount() int32 {
	if o == nil || IsNil(o.ModuleTypeCount) {
		var ret int32
		return ret
	}
	return *o.ModuleTypeCount
}

// GetModuleTypeCountOk returns a tuple with the ModuleTypeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetModuleTypeCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ModuleTypeCount) {
		return nil, false
	}
	return o.ModuleTypeCount, true
}

// HasModuleTypeCount returns a boolean if a field has been set.
func (o *ModuleFamily) HasModuleTypeCount() bool {
	if o != nil && !IsNil(o.ModuleTypeCount) {
		return true
	}

	return false
}

// SetModuleTypeCount gets a reference to the given int32 and assigns it to the ModuleTypeCount field.
func (o *ModuleFamily) SetModuleTypeCount(v int32) {
	o.ModuleTypeCount = &v
}

// GetModuleBayCount returns the ModuleBayCount field value if set, zero value otherwise.
func (o *ModuleFamily) GetModuleBayCount() int32 {
	if o == nil || IsNil(o.ModuleBayCount) {
		var ret int32
		return ret
	}
	return *o.ModuleBayCount
}

// GetModuleBayCountOk returns a tuple with the ModuleBayCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetModuleBayCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ModuleBayCount) {
		return nil, false
	}
	return o.ModuleBayCount, true
}

// HasModuleBayCount returns a boolean if a field has been set.
func (o *ModuleFamily) HasModuleBayCount() bool {
	if o != nil && !IsNil(o.ModuleBayCount) {
		return true
	}

	return false
}

// SetModuleBayCount gets a reference to the given int32 and assigns it to the ModuleBayCount field.
func (o *ModuleFamily) SetModuleBayCount(v int32) {
	o.ModuleBayCount = &v
}

// GetName returns the Name field value
func (o *ModuleFamily) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ModuleFamily) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *ModuleFamily) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *ModuleFamily) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *ModuleFamily) SetDescription(v string) {
	o.Description = &v
}

// GetCreated returns the Created field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ModuleFamily) GetCreated() time.Time {
	if o == nil || o.Created.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModuleFamily) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// SetCreated sets field value
func (o *ModuleFamily) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// GetLastUpdated returns the LastUpdated field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ModuleFamily) GetLastUpdated() time.Time {
	if o == nil || o.LastUpdated.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ModuleFamily) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// SetLastUpdated sets field value
func (o *ModuleFamily) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

// GetNotesUrl returns the NotesUrl field value
func (o *ModuleFamily) GetNotesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotesUrl
}

// GetNotesUrlOk returns a tuple with the NotesUrl field value
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetNotesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotesUrl, true
}

// SetNotesUrl sets field value
func (o *ModuleFamily) SetNotesUrl(v string) {
	o.NotesUrl = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *ModuleFamily) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ModuleFamily) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *ModuleFamily) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *ModuleFamily) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o ModuleFamily) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ModuleFamily) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["object_type"] = o.ObjectType
	toSerialize["display"] = o.Display
	toSerialize["url"] = o.Url
	toSerialize["natural_slug"] = o.NaturalSlug
	if !IsNil(o.ModuleTypeCount) {
		toSerialize["module_type_count"] = o.ModuleTypeCount
	}
	if !IsNil(o.ModuleBayCount) {
		toSerialize["module_bay_count"] = o.ModuleBayCount
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["created"] = o.Created.Get()
	toSerialize["last_updated"] = o.LastUpdated.Get()
	toSerialize["notes_url"] = o.NotesUrl
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ModuleFamily) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_type",
		"display",
		"url",
		"natural_slug",
		"name",
		"created",
		"last_updated",
		"notes_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varModuleFamily := _ModuleFamily{}

	err = json.Unmarshal(data, &varModuleFamily)

	if err != nil {
		return err
	}

	*o = ModuleFamily(varModuleFamily)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "display")
		delete(additionalProperties, "url")
		delete(additionalProperties, "natural_slug")
		delete(additionalProperties, "module_type_count")
		delete(additionalProperties, "module_bay_count")
		delete(additionalProperties, "name")
		delete(additionalProperties, "description")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "notes_url")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableModuleFamily struct {
	value *ModuleFamily
	isSet bool
}

func (v NullableModuleFamily) Get() *ModuleFamily {
	return v.value
}

func (v *NullableModuleFamily) Set(val *ModuleFamily) {
	v.value = val
	v.isSet = true
}

func (v NullableModuleFamily) IsSet() bool {
	return v.isSet
}

func (v *NullableModuleFamily) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableModuleFamily(val *ModuleFamily) *NullableModuleFamily {
	return &NullableModuleFamily{value: val, isSet: true}
}

func (v NullableModuleFamily) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableModuleFamily) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


