/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// EncryptionAlgorithmEnum the model 'EncryptionAlgorithmEnum'
type EncryptionAlgorithmEnum string

// List of EncryptionAlgorithmEnum
const (
	ENCRYPTIONALGORITHMENUM_AES_128_CBC EncryptionAlgorithmEnum = "AES-128-CBC"
	ENCRYPTIONALGORITHMENUM_AES_128_GCM EncryptionAlgorithmEnum = "AES-128-GCM"
	ENCRYPTIONALGORITHMENUM_AES_192_CBC EncryptionAlgorithmEnum = "AES-192-CBC"
	ENCRYPTIONALGORITHMENUM_AES_192_GCM EncryptionAlgorithmEnum = "AES-192-GCM"
	ENCRYPTIONALGORITHMENUM_AES_256_CBC EncryptionAlgorithmEnum = "AES-256-CBC"
	ENCRYPTIONALGORITHMENUM_AES_256_GCM EncryptionAlgorithmEnum = "AES-256-GCM"
	ENCRYPTIONALGORITHMENUM_DES EncryptionAlgorithmEnum = "DES"
	ENCRYPTIONALGORITHMENUM__3_DES EncryptionAlgorithmEnum = "3DES"
)

// All allowed values of EncryptionAlgorithmEnum enum
var AllowedEncryptionAlgorithmEnumEnumValues = []EncryptionAlgorithmEnum{
	"AES-128-CBC",
	"AES-128-GCM",
	"AES-192-CBC",
	"AES-192-GCM",
	"AES-256-CBC",
	"AES-256-GCM",
	"DES",
	"3DES",
}

func (v *EncryptionAlgorithmEnum) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := EncryptionAlgorithmEnum(value)
	for _, existing := range AllowedEncryptionAlgorithmEnumEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid EncryptionAlgorithmEnum", value)
}

// NewEncryptionAlgorithmEnumFromValue returns a pointer to a valid EncryptionAlgorithmEnum
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewEncryptionAlgorithmEnumFromValue(v string) (*EncryptionAlgorithmEnum, error) {
	ev := EncryptionAlgorithmEnum(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for EncryptionAlgorithmEnum: valid values are %v", v, AllowedEncryptionAlgorithmEnumEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v EncryptionAlgorithmEnum) IsValid() bool {
	for _, existing := range AllowedEncryptionAlgorithmEnumEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to EncryptionAlgorithmEnum value
func (v EncryptionAlgorithmEnum) Ptr() *EncryptionAlgorithmEnum {
	return &v
}

type NullableEncryptionAlgorithmEnum struct {
	value *EncryptionAlgorithmEnum
	isSet bool
}

func (v NullableEncryptionAlgorithmEnum) Get() *EncryptionAlgorithmEnum {
	return v.value
}

func (v *NullableEncryptionAlgorithmEnum) Set(val *EncryptionAlgorithmEnum) {
	v.value = val
	v.isSet = true
}

func (v NullableEncryptionAlgorithmEnum) IsSet() bool {
	return v.isSet
}

func (v *NullableEncryptionAlgorithmEnum) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEncryptionAlgorithmEnum(val *EncryptionAlgorithmEnum) *NullableEncryptionAlgorithmEnum {
	return &NullableEncryptionAlgorithmEnum{value: val, isSet: true}
}

func (v NullableEncryptionAlgorithmEnum) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEncryptionAlgorithmEnum) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

