/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkWritablePowerPanelRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkWritablePowerPanelRequest{}

// BulkWritablePowerPanelRequest Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
type BulkWritablePowerPanelRequest struct {
	Id string `json:"id"`
	PanelType *PanelTypeEnum `json:"panel_type,omitempty"`
	PowerPath *PowerPathEnum `json:"power_path,omitempty"`
	Name string `json:"name"`
	// Total number of breaker positions in the panel (e.g., 42)
	BreakerPositionCount NullableInt32 `json:"breaker_position_count,omitempty"`
	Location BulkWritableCableRequestStatus `json:"location"`
	RackGroup NullableApprovalWorkflowUser `json:"rack_group,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Relationships *map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue `json:"relationships,omitempty"`
	Tags []BulkWritableCableRequestStatus `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkWritablePowerPanelRequest BulkWritablePowerPanelRequest

// NewBulkWritablePowerPanelRequest instantiates a new BulkWritablePowerPanelRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkWritablePowerPanelRequest(id string, name string, location BulkWritableCableRequestStatus) *BulkWritablePowerPanelRequest {
	this := BulkWritablePowerPanelRequest{}
	this.Id = id
	this.Name = name
	this.Location = location
	return &this
}

// NewBulkWritablePowerPanelRequestWithDefaults instantiates a new BulkWritablePowerPanelRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkWritablePowerPanelRequestWithDefaults() *BulkWritablePowerPanelRequest {
	this := BulkWritablePowerPanelRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkWritablePowerPanelRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkWritablePowerPanelRequest) SetId(v string) {
	o.Id = v
}

// GetPanelType returns the PanelType field value if set, zero value otherwise.
func (o *BulkWritablePowerPanelRequest) GetPanelType() PanelTypeEnum {
	if o == nil || IsNil(o.PanelType) {
		var ret PanelTypeEnum
		return ret
	}
	return *o.PanelType
}

// GetPanelTypeOk returns a tuple with the PanelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetPanelTypeOk() (*PanelTypeEnum, bool) {
	if o == nil || IsNil(o.PanelType) {
		return nil, false
	}
	return o.PanelType, true
}

// HasPanelType returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasPanelType() bool {
	if o != nil && !IsNil(o.PanelType) {
		return true
	}

	return false
}

// SetPanelType gets a reference to the given PanelTypeEnum and assigns it to the PanelType field.
func (o *BulkWritablePowerPanelRequest) SetPanelType(v PanelTypeEnum) {
	o.PanelType = &v
}

// GetPowerPath returns the PowerPath field value if set, zero value otherwise.
func (o *BulkWritablePowerPanelRequest) GetPowerPath() PowerPathEnum {
	if o == nil || IsNil(o.PowerPath) {
		var ret PowerPathEnum
		return ret
	}
	return *o.PowerPath
}

// GetPowerPathOk returns a tuple with the PowerPath field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetPowerPathOk() (*PowerPathEnum, bool) {
	if o == nil || IsNil(o.PowerPath) {
		return nil, false
	}
	return o.PowerPath, true
}

// HasPowerPath returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasPowerPath() bool {
	if o != nil && !IsNil(o.PowerPath) {
		return true
	}

	return false
}

// SetPowerPath gets a reference to the given PowerPathEnum and assigns it to the PowerPath field.
func (o *BulkWritablePowerPanelRequest) SetPowerPath(v PowerPathEnum) {
	o.PowerPath = &v
}

// GetName returns the Name field value
func (o *BulkWritablePowerPanelRequest) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *BulkWritablePowerPanelRequest) SetName(v string) {
	o.Name = v
}

// GetBreakerPositionCount returns the BreakerPositionCount field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkWritablePowerPanelRequest) GetBreakerPositionCount() int32 {
	if o == nil || IsNil(o.BreakerPositionCount.Get()) {
		var ret int32
		return ret
	}
	return *o.BreakerPositionCount.Get()
}

// GetBreakerPositionCountOk returns a tuple with the BreakerPositionCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkWritablePowerPanelRequest) GetBreakerPositionCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.BreakerPositionCount.Get(), o.BreakerPositionCount.IsSet()
}

// HasBreakerPositionCount returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasBreakerPositionCount() bool {
	if o != nil && o.BreakerPositionCount.IsSet() {
		return true
	}

	return false
}

// SetBreakerPositionCount gets a reference to the given NullableInt32 and assigns it to the BreakerPositionCount field.
func (o *BulkWritablePowerPanelRequest) SetBreakerPositionCount(v int32) {
	o.BreakerPositionCount.Set(&v)
}
// SetBreakerPositionCountNil sets the value for BreakerPositionCount to be an explicit nil
func (o *BulkWritablePowerPanelRequest) SetBreakerPositionCountNil() {
	o.BreakerPositionCount.Set(nil)
}

// UnsetBreakerPositionCount ensures that no value is present for BreakerPositionCount, not even an explicit nil
func (o *BulkWritablePowerPanelRequest) UnsetBreakerPositionCount() {
	o.BreakerPositionCount.Unset()
}

// GetLocation returns the Location field value
func (o *BulkWritablePowerPanelRequest) GetLocation() BulkWritableCableRequestStatus {
	if o == nil {
		var ret BulkWritableCableRequestStatus
		return ret
	}

	return o.Location
}

// GetLocationOk returns a tuple with the Location field value
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetLocationOk() (*BulkWritableCableRequestStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Location, true
}

// SetLocation sets field value
func (o *BulkWritablePowerPanelRequest) SetLocation(v BulkWritableCableRequestStatus) {
	o.Location = v
}

// GetRackGroup returns the RackGroup field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkWritablePowerPanelRequest) GetRackGroup() ApprovalWorkflowUser {
	if o == nil || IsNil(o.RackGroup.Get()) {
		var ret ApprovalWorkflowUser
		return ret
	}
	return *o.RackGroup.Get()
}

// GetRackGroupOk returns a tuple with the RackGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkWritablePowerPanelRequest) GetRackGroupOk() (*ApprovalWorkflowUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.RackGroup.Get(), o.RackGroup.IsSet()
}

// HasRackGroup returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasRackGroup() bool {
	if o != nil && o.RackGroup.IsSet() {
		return true
	}

	return false
}

// SetRackGroup gets a reference to the given NullableApprovalWorkflowUser and assigns it to the RackGroup field.
func (o *BulkWritablePowerPanelRequest) SetRackGroup(v ApprovalWorkflowUser) {
	o.RackGroup.Set(&v)
}
// SetRackGroupNil sets the value for RackGroup to be an explicit nil
func (o *BulkWritablePowerPanelRequest) SetRackGroupNil() {
	o.RackGroup.Set(nil)
}

// UnsetRackGroup ensures that no value is present for RackGroup, not even an explicit nil
func (o *BulkWritablePowerPanelRequest) UnsetRackGroup() {
	o.RackGroup.Unset()
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *BulkWritablePowerPanelRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *BulkWritablePowerPanelRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *BulkWritablePowerPanelRequest) GetRelationships() map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue {
	if o == nil || IsNil(o.Relationships) {
		var ret map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetRelationshipsOk() (*map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue and assigns it to the Relationships field.
func (o *BulkWritablePowerPanelRequest) SetRelationships(v map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue) {
	o.Relationships = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *BulkWritablePowerPanelRequest) GetTags() []BulkWritableCableRequestStatus {
	if o == nil || IsNil(o.Tags) {
		var ret []BulkWritableCableRequestStatus
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritablePowerPanelRequest) GetTagsOk() ([]BulkWritableCableRequestStatus, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *BulkWritablePowerPanelRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []BulkWritableCableRequestStatus and assigns it to the Tags field.
func (o *BulkWritablePowerPanelRequest) SetTags(v []BulkWritableCableRequestStatus) {
	o.Tags = v
}

func (o BulkWritablePowerPanelRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkWritablePowerPanelRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.PanelType) {
		toSerialize["panel_type"] = o.PanelType
	}
	if !IsNil(o.PowerPath) {
		toSerialize["power_path"] = o.PowerPath
	}
	toSerialize["name"] = o.Name
	if o.BreakerPositionCount.IsSet() {
		toSerialize["breaker_position_count"] = o.BreakerPositionCount.Get()
	}
	toSerialize["location"] = o.Location
	if o.RackGroup.IsSet() {
		toSerialize["rack_group"] = o.RackGroup.Get()
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkWritablePowerPanelRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"name",
		"location",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkWritablePowerPanelRequest := _BulkWritablePowerPanelRequest{}

	err = json.Unmarshal(data, &varBulkWritablePowerPanelRequest)

	if err != nil {
		return err
	}

	*o = BulkWritablePowerPanelRequest(varBulkWritablePowerPanelRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "panel_type")
		delete(additionalProperties, "power_path")
		delete(additionalProperties, "name")
		delete(additionalProperties, "breaker_position_count")
		delete(additionalProperties, "location")
		delete(additionalProperties, "rack_group")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "relationships")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkWritablePowerPanelRequest struct {
	value *BulkWritablePowerPanelRequest
	isSet bool
}

func (v NullableBulkWritablePowerPanelRequest) Get() *BulkWritablePowerPanelRequest {
	return v.value
}

func (v *NullableBulkWritablePowerPanelRequest) Set(val *BulkWritablePowerPanelRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWritablePowerPanelRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWritablePowerPanelRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWritablePowerPanelRequest(val *BulkWritablePowerPanelRequest) *NullableBulkWritablePowerPanelRequest {
	return &NullableBulkWritablePowerPanelRequest{value: val, isSet: true}
}

func (v NullableBulkWritablePowerPanelRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWritablePowerPanelRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


