/*
API Documentation

Source of truth and network automation platform

API version: 3.0.11 (3.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
)

// checks if the BulkWritableVPNTunnelRequestVpn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkWritableVPNTunnelRequestVpn{}

// BulkWritableVPNTunnelRequestVpn VPN to which this tunnel belongs
type BulkWritableVPNTunnelRequestVpn struct {
	Id *ApprovalWorkflowApprovalWorkflowDefinitionId `json:"id,omitempty"`
	ObjectType *string `json:"object_type,omitempty" validate:"regexp=^[a-z][a-z0-9_]+\\.[a-z][a-z0-9_]+$"`
	Url *string `json:"url,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkWritableVPNTunnelRequestVpn BulkWritableVPNTunnelRequestVpn

// NewBulkWritableVPNTunnelRequestVpn instantiates a new BulkWritableVPNTunnelRequestVpn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkWritableVPNTunnelRequestVpn() *BulkWritableVPNTunnelRequestVpn {
	this := BulkWritableVPNTunnelRequestVpn{}
	return &this
}

// NewBulkWritableVPNTunnelRequestVpnWithDefaults instantiates a new BulkWritableVPNTunnelRequestVpn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkWritableVPNTunnelRequestVpnWithDefaults() *BulkWritableVPNTunnelRequestVpn {
	this := BulkWritableVPNTunnelRequestVpn{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *BulkWritableVPNTunnelRequestVpn) GetId() ApprovalWorkflowApprovalWorkflowDefinitionId {
	if o == nil || IsNil(o.Id) {
		var ret ApprovalWorkflowApprovalWorkflowDefinitionId
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableVPNTunnelRequestVpn) GetIdOk() (*ApprovalWorkflowApprovalWorkflowDefinitionId, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *BulkWritableVPNTunnelRequestVpn) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given ApprovalWorkflowApprovalWorkflowDefinitionId and assigns it to the Id field.
func (o *BulkWritableVPNTunnelRequestVpn) SetId(v ApprovalWorkflowApprovalWorkflowDefinitionId) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value if set, zero value otherwise.
func (o *BulkWritableVPNTunnelRequestVpn) GetObjectType() string {
	if o == nil || IsNil(o.ObjectType) {
		var ret string
		return ret
	}
	return *o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableVPNTunnelRequestVpn) GetObjectTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ObjectType) {
		return nil, false
	}
	return o.ObjectType, true
}

// HasObjectType returns a boolean if a field has been set.
func (o *BulkWritableVPNTunnelRequestVpn) HasObjectType() bool {
	if o != nil && !IsNil(o.ObjectType) {
		return true
	}

	return false
}

// SetObjectType gets a reference to the given string and assigns it to the ObjectType field.
func (o *BulkWritableVPNTunnelRequestVpn) SetObjectType(v string) {
	o.ObjectType = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *BulkWritableVPNTunnelRequestVpn) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableVPNTunnelRequestVpn) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *BulkWritableVPNTunnelRequestVpn) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *BulkWritableVPNTunnelRequestVpn) SetUrl(v string) {
	o.Url = &v
}

func (o BulkWritableVPNTunnelRequestVpn) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkWritableVPNTunnelRequestVpn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.ObjectType) {
		toSerialize["object_type"] = o.ObjectType
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkWritableVPNTunnelRequestVpn) UnmarshalJSON(data []byte) (err error) {
	varBulkWritableVPNTunnelRequestVpn := _BulkWritableVPNTunnelRequestVpn{}

	err = json.Unmarshal(data, &varBulkWritableVPNTunnelRequestVpn)

	if err != nil {
		return err
	}

	*o = BulkWritableVPNTunnelRequestVpn(varBulkWritableVPNTunnelRequestVpn)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "url")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkWritableVPNTunnelRequestVpn struct {
	value *BulkWritableVPNTunnelRequestVpn
	isSet bool
}

func (v NullableBulkWritableVPNTunnelRequestVpn) Get() *BulkWritableVPNTunnelRequestVpn {
	return v.value
}

func (v *NullableBulkWritableVPNTunnelRequestVpn) Set(val *BulkWritableVPNTunnelRequestVpn) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWritableVPNTunnelRequestVpn) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWritableVPNTunnelRequestVpn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWritableVPNTunnelRequestVpn(val *BulkWritableVPNTunnelRequestVpn) *NullableBulkWritableVPNTunnelRequestVpn {
	return &NullableBulkWritableVPNTunnelRequestVpn{value: val, isSet: true}
}

func (v NullableBulkWritableVPNTunnelRequestVpn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWritableVPNTunnelRequestVpn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


