/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// RedundancyProtocol1 the model 'RedundancyProtocol1'
type RedundancyProtocol1 string

// List of Redundancy_Protocol_1
const (
	REDUNDANCYPROTOCOL1_HSRP RedundancyProtocol1 = "hsrp"
	REDUNDANCYPROTOCOL1_VRRP RedundancyProtocol1 = "vrrp"
	REDUNDANCYPROTOCOL1_GLBP RedundancyProtocol1 = "glbp"
	REDUNDANCYPROTOCOL1_CARP RedundancyProtocol1 = "carp"
	REDUNDANCYPROTOCOL1_EMPTY RedundancyProtocol1 = ""
)

// All allowed values of RedundancyProtocol1 enum
var AllowedRedundancyProtocol1EnumValues = []RedundancyProtocol1{
	"hsrp",
	"vrrp",
	"glbp",
	"carp",
	"",
}

func (v *RedundancyProtocol1) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := RedundancyProtocol1(value)
	for _, existing := range AllowedRedundancyProtocol1EnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid RedundancyProtocol1", value)
}

// NewRedundancyProtocol1FromValue returns a pointer to a valid RedundancyProtocol1
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewRedundancyProtocol1FromValue(v string) (*RedundancyProtocol1, error) {
	ev := RedundancyProtocol1(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for RedundancyProtocol1: valid values are %v", v, AllowedRedundancyProtocol1EnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v RedundancyProtocol1) IsValid() bool {
	for _, existing := range AllowedRedundancyProtocol1EnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to Redundancy_Protocol_1 value
func (v RedundancyProtocol1) Ptr() *RedundancyProtocol1 {
	return &v
}

type NullableRedundancyProtocol1 struct {
	value *RedundancyProtocol1
	isSet bool
}

func (v NullableRedundancyProtocol1) Get() *RedundancyProtocol1 {
	return v.value
}

func (v *NullableRedundancyProtocol1) Set(val *RedundancyProtocol1) {
	v.value = val
	v.isSet = true
}

func (v NullableRedundancyProtocol1) IsSet() bool {
	return v.isSet
}

func (v *NullableRedundancyProtocol1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRedundancyProtocol1(val *RedundancyProtocol1) *NullableRedundancyProtocol1 {
	return &NullableRedundancyProtocol1{value: val, isSet: true}
}

func (v NullableRedundancyProtocol1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRedundancyProtocol1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

