/*
API Documentation

Source of truth and network automation platform

API version: 3.0.11 (3.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the ApprovalWorkflow type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApprovalWorkflow{}

// ApprovalWorkflow ApprovalWorkflow Serializer.
type ApprovalWorkflow struct {
	Id *string `json:"id,omitempty"`
	ObjectType string `json:"object_type" validate:"regexp=^[a-z][a-z0-9_]+\\.[a-z][a-z0-9_]+$"`
	// Human friendly display value
	Display string `json:"display"`
	Url string `json:"url"`
	NaturalSlug string `json:"natural_slug"`
	ObjectUnderReviewContentType string `json:"object_under_review_content_type"`
	DecisionDate NullableTime `json:"decision_date"`
	ObjectUnderReviewObjectId string `json:"object_under_review_object_id"`
	// Current state of the approval workflow. Eligible values are: Pending, Approved, Denied, Canceled.
	CurrentState *ApprovalWorkflowStateChoices `json:"current_state,omitempty"`
	UserName string `json:"user_name"`
	ApprovalWorkflowDefinition ApprovalWorkflowApprovalWorkflowDefinition `json:"approval_workflow_definition"`
	User NullableApprovalWorkflowUser `json:"user,omitempty"`
	Created NullableTime `json:"created"`
	LastUpdated NullableTime `json:"last_updated"`
	NotesUrl string `json:"notes_url"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _ApprovalWorkflow ApprovalWorkflow

// NewApprovalWorkflow instantiates a new ApprovalWorkflow object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApprovalWorkflow(objectType string, display string, url string, naturalSlug string, objectUnderReviewContentType string, decisionDate NullableTime, objectUnderReviewObjectId string, userName string, approvalWorkflowDefinition ApprovalWorkflowApprovalWorkflowDefinition, created NullableTime, lastUpdated NullableTime, notesUrl string) *ApprovalWorkflow {
	this := ApprovalWorkflow{}
	this.ObjectType = objectType
	this.Display = display
	this.Url = url
	this.NaturalSlug = naturalSlug
	this.ObjectUnderReviewContentType = objectUnderReviewContentType
	this.DecisionDate = decisionDate
	this.ObjectUnderReviewObjectId = objectUnderReviewObjectId
	this.UserName = userName
	this.ApprovalWorkflowDefinition = approvalWorkflowDefinition
	this.Created = created
	this.LastUpdated = lastUpdated
	this.NotesUrl = notesUrl
	return &this
}

// NewApprovalWorkflowWithDefaults instantiates a new ApprovalWorkflow object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApprovalWorkflowWithDefaults() *ApprovalWorkflow {
	this := ApprovalWorkflow{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ApprovalWorkflow) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ApprovalWorkflow) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ApprovalWorkflow) SetId(v string) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value
func (o *ApprovalWorkflow) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *ApprovalWorkflow) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDisplay returns the Display field value
func (o *ApprovalWorkflow) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *ApprovalWorkflow) SetDisplay(v string) {
	o.Display = v
}

// GetUrl returns the Url field value
func (o *ApprovalWorkflow) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *ApprovalWorkflow) SetUrl(v string) {
	o.Url = v
}

// GetNaturalSlug returns the NaturalSlug field value
func (o *ApprovalWorkflow) GetNaturalSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NaturalSlug
}

// GetNaturalSlugOk returns a tuple with the NaturalSlug field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetNaturalSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NaturalSlug, true
}

// SetNaturalSlug sets field value
func (o *ApprovalWorkflow) SetNaturalSlug(v string) {
	o.NaturalSlug = v
}

// GetObjectUnderReviewContentType returns the ObjectUnderReviewContentType field value
func (o *ApprovalWorkflow) GetObjectUnderReviewContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectUnderReviewContentType
}

// GetObjectUnderReviewContentTypeOk returns a tuple with the ObjectUnderReviewContentType field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetObjectUnderReviewContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectUnderReviewContentType, true
}

// SetObjectUnderReviewContentType sets field value
func (o *ApprovalWorkflow) SetObjectUnderReviewContentType(v string) {
	o.ObjectUnderReviewContentType = v
}

// GetDecisionDate returns the DecisionDate field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ApprovalWorkflow) GetDecisionDate() time.Time {
	if o == nil || o.DecisionDate.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.DecisionDate.Get()
}

// GetDecisionDateOk returns a tuple with the DecisionDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalWorkflow) GetDecisionDateOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.DecisionDate.Get(), o.DecisionDate.IsSet()
}

// SetDecisionDate sets field value
func (o *ApprovalWorkflow) SetDecisionDate(v time.Time) {
	o.DecisionDate.Set(&v)
}

// GetObjectUnderReviewObjectId returns the ObjectUnderReviewObjectId field value
func (o *ApprovalWorkflow) GetObjectUnderReviewObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectUnderReviewObjectId
}

// GetObjectUnderReviewObjectIdOk returns a tuple with the ObjectUnderReviewObjectId field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetObjectUnderReviewObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectUnderReviewObjectId, true
}

// SetObjectUnderReviewObjectId sets field value
func (o *ApprovalWorkflow) SetObjectUnderReviewObjectId(v string) {
	o.ObjectUnderReviewObjectId = v
}

// GetCurrentState returns the CurrentState field value if set, zero value otherwise.
func (o *ApprovalWorkflow) GetCurrentState() ApprovalWorkflowStateChoices {
	if o == nil || IsNil(o.CurrentState) {
		var ret ApprovalWorkflowStateChoices
		return ret
	}
	return *o.CurrentState
}

// GetCurrentStateOk returns a tuple with the CurrentState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetCurrentStateOk() (*ApprovalWorkflowStateChoices, bool) {
	if o == nil || IsNil(o.CurrentState) {
		return nil, false
	}
	return o.CurrentState, true
}

// HasCurrentState returns a boolean if a field has been set.
func (o *ApprovalWorkflow) HasCurrentState() bool {
	if o != nil && !IsNil(o.CurrentState) {
		return true
	}

	return false
}

// SetCurrentState gets a reference to the given ApprovalWorkflowStateChoices and assigns it to the CurrentState field.
func (o *ApprovalWorkflow) SetCurrentState(v ApprovalWorkflowStateChoices) {
	o.CurrentState = &v
}

// GetUserName returns the UserName field value
func (o *ApprovalWorkflow) GetUserName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserName
}

// GetUserNameOk returns a tuple with the UserName field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetUserNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserName, true
}

// SetUserName sets field value
func (o *ApprovalWorkflow) SetUserName(v string) {
	o.UserName = v
}

// GetApprovalWorkflowDefinition returns the ApprovalWorkflowDefinition field value
func (o *ApprovalWorkflow) GetApprovalWorkflowDefinition() ApprovalWorkflowApprovalWorkflowDefinition {
	if o == nil {
		var ret ApprovalWorkflowApprovalWorkflowDefinition
		return ret
	}

	return o.ApprovalWorkflowDefinition
}

// GetApprovalWorkflowDefinitionOk returns a tuple with the ApprovalWorkflowDefinition field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetApprovalWorkflowDefinitionOk() (*ApprovalWorkflowApprovalWorkflowDefinition, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ApprovalWorkflowDefinition, true
}

// SetApprovalWorkflowDefinition sets field value
func (o *ApprovalWorkflow) SetApprovalWorkflowDefinition(v ApprovalWorkflowApprovalWorkflowDefinition) {
	o.ApprovalWorkflowDefinition = v
}

// GetUser returns the User field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ApprovalWorkflow) GetUser() ApprovalWorkflowUser {
	if o == nil || IsNil(o.User.Get()) {
		var ret ApprovalWorkflowUser
		return ret
	}
	return *o.User.Get()
}

// GetUserOk returns a tuple with the User field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalWorkflow) GetUserOk() (*ApprovalWorkflowUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.User.Get(), o.User.IsSet()
}

// HasUser returns a boolean if a field has been set.
func (o *ApprovalWorkflow) HasUser() bool {
	if o != nil && o.User.IsSet() {
		return true
	}

	return false
}

// SetUser gets a reference to the given NullableApprovalWorkflowUser and assigns it to the User field.
func (o *ApprovalWorkflow) SetUser(v ApprovalWorkflowUser) {
	o.User.Set(&v)
}
// SetUserNil sets the value for User to be an explicit nil
func (o *ApprovalWorkflow) SetUserNil() {
	o.User.Set(nil)
}

// UnsetUser ensures that no value is present for User, not even an explicit nil
func (o *ApprovalWorkflow) UnsetUser() {
	o.User.Unset()
}

// GetCreated returns the Created field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ApprovalWorkflow) GetCreated() time.Time {
	if o == nil || o.Created.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalWorkflow) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// SetCreated sets field value
func (o *ApprovalWorkflow) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// GetLastUpdated returns the LastUpdated field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *ApprovalWorkflow) GetLastUpdated() time.Time {
	if o == nil || o.LastUpdated.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApprovalWorkflow) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// SetLastUpdated sets field value
func (o *ApprovalWorkflow) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

// GetNotesUrl returns the NotesUrl field value
func (o *ApprovalWorkflow) GetNotesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotesUrl
}

// GetNotesUrlOk returns a tuple with the NotesUrl field value
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetNotesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotesUrl, true
}

// SetNotesUrl sets field value
func (o *ApprovalWorkflow) SetNotesUrl(v string) {
	o.NotesUrl = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *ApprovalWorkflow) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApprovalWorkflow) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *ApprovalWorkflow) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *ApprovalWorkflow) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

func (o ApprovalWorkflow) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApprovalWorkflow) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["object_type"] = o.ObjectType
	toSerialize["display"] = o.Display
	toSerialize["url"] = o.Url
	toSerialize["natural_slug"] = o.NaturalSlug
	toSerialize["object_under_review_content_type"] = o.ObjectUnderReviewContentType
	toSerialize["decision_date"] = o.DecisionDate.Get()
	toSerialize["object_under_review_object_id"] = o.ObjectUnderReviewObjectId
	if !IsNil(o.CurrentState) {
		toSerialize["current_state"] = o.CurrentState
	}
	toSerialize["user_name"] = o.UserName
	toSerialize["approval_workflow_definition"] = o.ApprovalWorkflowDefinition
	if o.User.IsSet() {
		toSerialize["user"] = o.User.Get()
	}
	toSerialize["created"] = o.Created.Get()
	toSerialize["last_updated"] = o.LastUpdated.Get()
	toSerialize["notes_url"] = o.NotesUrl
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *ApprovalWorkflow) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_type",
		"display",
		"url",
		"natural_slug",
		"object_under_review_content_type",
		"decision_date",
		"object_under_review_object_id",
		"user_name",
		"approval_workflow_definition",
		"created",
		"last_updated",
		"notes_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApprovalWorkflow := _ApprovalWorkflow{}

	err = json.Unmarshal(data, &varApprovalWorkflow)

	if err != nil {
		return err
	}

	*o = ApprovalWorkflow(varApprovalWorkflow)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "display")
		delete(additionalProperties, "url")
		delete(additionalProperties, "natural_slug")
		delete(additionalProperties, "object_under_review_content_type")
		delete(additionalProperties, "decision_date")
		delete(additionalProperties, "object_under_review_object_id")
		delete(additionalProperties, "current_state")
		delete(additionalProperties, "user_name")
		delete(additionalProperties, "approval_workflow_definition")
		delete(additionalProperties, "user")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "notes_url")
		delete(additionalProperties, "custom_fields")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableApprovalWorkflow struct {
	value *ApprovalWorkflow
	isSet bool
}

func (v NullableApprovalWorkflow) Get() *ApprovalWorkflow {
	return v.value
}

func (v *NullableApprovalWorkflow) Set(val *ApprovalWorkflow) {
	v.value = val
	v.isSet = true
}

func (v NullableApprovalWorkflow) IsSet() bool {
	return v.isSet
}

func (v *NullableApprovalWorkflow) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApprovalWorkflow(val *ApprovalWorkflow) *NullableApprovalWorkflow {
	return &NullableApprovalWorkflow{value: val, isSet: true}
}

func (v NullableApprovalWorkflow) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApprovalWorkflow) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


