/*
API Documentation

Source of truth and network automation platform

API version: 2.4.21 (2.4)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"time"
	"fmt"
)

// checks if the RadioProfile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RadioProfile{}

// RadioProfile Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
type RadioProfile struct {
	Id *string `json:"id,omitempty"`
	ObjectType string `json:"object_type" validate:"regexp=^[a-z][a-z0-9_]+\\\\.[a-z][a-z0-9_]+$"`
	// Human friendly display value
	Display string `json:"display"`
	Url string `json:"url"`
	NaturalSlug string `json:"natural_slug"`
	ChannelWidth []RadioProfileChannelWidthInner `json:"channel_width,omitempty"`
	AllowedChannelList []int32 `json:"allowed_channel_list,omitempty"`
	Name string `json:"name"`
	Frequency *BulkWritableRadioProfileRequestFrequency `json:"frequency,omitempty"`
	TxPowerMin NullableInt32 `json:"tx_power_min,omitempty"`
	TxPowerMax NullableInt32 `json:"tx_power_max,omitempty"`
	RegulatoryDomain RegulatoryDomainEnum `json:"regulatory_domain"`
	RxPowerMin NullableInt32 `json:"rx_power_min,omitempty"`
	SupportedDataRates []BulkWritableCableRequestStatus `json:"supported_data_rates,omitempty"`
	Created NullableTime `json:"created"`
	LastUpdated NullableTime `json:"last_updated"`
	NotesUrl string `json:"notes_url"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Tags []BulkWritableCableRequestStatus `json:"tags,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _RadioProfile RadioProfile

// NewRadioProfile instantiates a new RadioProfile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRadioProfile(objectType string, display string, url string, naturalSlug string, name string, regulatoryDomain RegulatoryDomainEnum, created NullableTime, lastUpdated NullableTime, notesUrl string) *RadioProfile {
	this := RadioProfile{}
	this.ObjectType = objectType
	this.Display = display
	this.Url = url
	this.NaturalSlug = naturalSlug
	this.Name = name
	this.RegulatoryDomain = regulatoryDomain
	this.Created = created
	this.LastUpdated = lastUpdated
	this.NotesUrl = notesUrl
	return &this
}

// NewRadioProfileWithDefaults instantiates a new RadioProfile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRadioProfileWithDefaults() *RadioProfile {
	this := RadioProfile{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *RadioProfile) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *RadioProfile) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *RadioProfile) SetId(v string) {
	o.Id = &v
}

// GetObjectType returns the ObjectType field value
func (o *RadioProfile) GetObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ObjectType
}

// GetObjectTypeOk returns a tuple with the ObjectType field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ObjectType, true
}

// SetObjectType sets field value
func (o *RadioProfile) SetObjectType(v string) {
	o.ObjectType = v
}

// GetDisplay returns the Display field value
func (o *RadioProfile) GetDisplay() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Display
}

// GetDisplayOk returns a tuple with the Display field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetDisplayOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Display, true
}

// SetDisplay sets field value
func (o *RadioProfile) SetDisplay(v string) {
	o.Display = v
}

// GetUrl returns the Url field value
func (o *RadioProfile) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *RadioProfile) SetUrl(v string) {
	o.Url = v
}

// GetNaturalSlug returns the NaturalSlug field value
func (o *RadioProfile) GetNaturalSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NaturalSlug
}

// GetNaturalSlugOk returns a tuple with the NaturalSlug field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetNaturalSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NaturalSlug, true
}

// SetNaturalSlug sets field value
func (o *RadioProfile) SetNaturalSlug(v string) {
	o.NaturalSlug = v
}

// GetChannelWidth returns the ChannelWidth field value if set, zero value otherwise.
func (o *RadioProfile) GetChannelWidth() []RadioProfileChannelWidthInner {
	if o == nil || IsNil(o.ChannelWidth) {
		var ret []RadioProfileChannelWidthInner
		return ret
	}
	return o.ChannelWidth
}

// GetChannelWidthOk returns a tuple with the ChannelWidth field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetChannelWidthOk() ([]RadioProfileChannelWidthInner, bool) {
	if o == nil || IsNil(o.ChannelWidth) {
		return nil, false
	}
	return o.ChannelWidth, true
}

// HasChannelWidth returns a boolean if a field has been set.
func (o *RadioProfile) HasChannelWidth() bool {
	if o != nil && !IsNil(o.ChannelWidth) {
		return true
	}

	return false
}

// SetChannelWidth gets a reference to the given []RadioProfileChannelWidthInner and assigns it to the ChannelWidth field.
func (o *RadioProfile) SetChannelWidth(v []RadioProfileChannelWidthInner) {
	o.ChannelWidth = v
}

// GetAllowedChannelList returns the AllowedChannelList field value if set, zero value otherwise.
func (o *RadioProfile) GetAllowedChannelList() []int32 {
	if o == nil || IsNil(o.AllowedChannelList) {
		var ret []int32
		return ret
	}
	return o.AllowedChannelList
}

// GetAllowedChannelListOk returns a tuple with the AllowedChannelList field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetAllowedChannelListOk() ([]int32, bool) {
	if o == nil || IsNil(o.AllowedChannelList) {
		return nil, false
	}
	return o.AllowedChannelList, true
}

// HasAllowedChannelList returns a boolean if a field has been set.
func (o *RadioProfile) HasAllowedChannelList() bool {
	if o != nil && !IsNil(o.AllowedChannelList) {
		return true
	}

	return false
}

// SetAllowedChannelList gets a reference to the given []int32 and assigns it to the AllowedChannelList field.
func (o *RadioProfile) SetAllowedChannelList(v []int32) {
	o.AllowedChannelList = v
}

// GetName returns the Name field value
func (o *RadioProfile) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *RadioProfile) SetName(v string) {
	o.Name = v
}

// GetFrequency returns the Frequency field value if set, zero value otherwise.
func (o *RadioProfile) GetFrequency() BulkWritableRadioProfileRequestFrequency {
	if o == nil || IsNil(o.Frequency) {
		var ret BulkWritableRadioProfileRequestFrequency
		return ret
	}
	return *o.Frequency
}

// GetFrequencyOk returns a tuple with the Frequency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetFrequencyOk() (*BulkWritableRadioProfileRequestFrequency, bool) {
	if o == nil || IsNil(o.Frequency) {
		return nil, false
	}
	return o.Frequency, true
}

// HasFrequency returns a boolean if a field has been set.
func (o *RadioProfile) HasFrequency() bool {
	if o != nil && !IsNil(o.Frequency) {
		return true
	}

	return false
}

// SetFrequency gets a reference to the given BulkWritableRadioProfileRequestFrequency and assigns it to the Frequency field.
func (o *RadioProfile) SetFrequency(v BulkWritableRadioProfileRequestFrequency) {
	o.Frequency = &v
}

// GetTxPowerMin returns the TxPowerMin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RadioProfile) GetTxPowerMin() int32 {
	if o == nil || IsNil(o.TxPowerMin.Get()) {
		var ret int32
		return ret
	}
	return *o.TxPowerMin.Get()
}

// GetTxPowerMinOk returns a tuple with the TxPowerMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RadioProfile) GetTxPowerMinOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TxPowerMin.Get(), o.TxPowerMin.IsSet()
}

// HasTxPowerMin returns a boolean if a field has been set.
func (o *RadioProfile) HasTxPowerMin() bool {
	if o != nil && o.TxPowerMin.IsSet() {
		return true
	}

	return false
}

// SetTxPowerMin gets a reference to the given NullableInt32 and assigns it to the TxPowerMin field.
func (o *RadioProfile) SetTxPowerMin(v int32) {
	o.TxPowerMin.Set(&v)
}
// SetTxPowerMinNil sets the value for TxPowerMin to be an explicit nil
func (o *RadioProfile) SetTxPowerMinNil() {
	o.TxPowerMin.Set(nil)
}

// UnsetTxPowerMin ensures that no value is present for TxPowerMin, not even an explicit nil
func (o *RadioProfile) UnsetTxPowerMin() {
	o.TxPowerMin.Unset()
}

// GetTxPowerMax returns the TxPowerMax field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RadioProfile) GetTxPowerMax() int32 {
	if o == nil || IsNil(o.TxPowerMax.Get()) {
		var ret int32
		return ret
	}
	return *o.TxPowerMax.Get()
}

// GetTxPowerMaxOk returns a tuple with the TxPowerMax field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RadioProfile) GetTxPowerMaxOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.TxPowerMax.Get(), o.TxPowerMax.IsSet()
}

// HasTxPowerMax returns a boolean if a field has been set.
func (o *RadioProfile) HasTxPowerMax() bool {
	if o != nil && o.TxPowerMax.IsSet() {
		return true
	}

	return false
}

// SetTxPowerMax gets a reference to the given NullableInt32 and assigns it to the TxPowerMax field.
func (o *RadioProfile) SetTxPowerMax(v int32) {
	o.TxPowerMax.Set(&v)
}
// SetTxPowerMaxNil sets the value for TxPowerMax to be an explicit nil
func (o *RadioProfile) SetTxPowerMaxNil() {
	o.TxPowerMax.Set(nil)
}

// UnsetTxPowerMax ensures that no value is present for TxPowerMax, not even an explicit nil
func (o *RadioProfile) UnsetTxPowerMax() {
	o.TxPowerMax.Unset()
}

// GetRegulatoryDomain returns the RegulatoryDomain field value
func (o *RadioProfile) GetRegulatoryDomain() RegulatoryDomainEnum {
	if o == nil {
		var ret RegulatoryDomainEnum
		return ret
	}

	return o.RegulatoryDomain
}

// GetRegulatoryDomainOk returns a tuple with the RegulatoryDomain field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetRegulatoryDomainOk() (*RegulatoryDomainEnum, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RegulatoryDomain, true
}

// SetRegulatoryDomain sets field value
func (o *RadioProfile) SetRegulatoryDomain(v RegulatoryDomainEnum) {
	o.RegulatoryDomain = v
}

// GetRxPowerMin returns the RxPowerMin field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *RadioProfile) GetRxPowerMin() int32 {
	if o == nil || IsNil(o.RxPowerMin.Get()) {
		var ret int32
		return ret
	}
	return *o.RxPowerMin.Get()
}

// GetRxPowerMinOk returns a tuple with the RxPowerMin field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RadioProfile) GetRxPowerMinOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return o.RxPowerMin.Get(), o.RxPowerMin.IsSet()
}

// HasRxPowerMin returns a boolean if a field has been set.
func (o *RadioProfile) HasRxPowerMin() bool {
	if o != nil && o.RxPowerMin.IsSet() {
		return true
	}

	return false
}

// SetRxPowerMin gets a reference to the given NullableInt32 and assigns it to the RxPowerMin field.
func (o *RadioProfile) SetRxPowerMin(v int32) {
	o.RxPowerMin.Set(&v)
}
// SetRxPowerMinNil sets the value for RxPowerMin to be an explicit nil
func (o *RadioProfile) SetRxPowerMinNil() {
	o.RxPowerMin.Set(nil)
}

// UnsetRxPowerMin ensures that no value is present for RxPowerMin, not even an explicit nil
func (o *RadioProfile) UnsetRxPowerMin() {
	o.RxPowerMin.Unset()
}

// GetSupportedDataRates returns the SupportedDataRates field value if set, zero value otherwise.
func (o *RadioProfile) GetSupportedDataRates() []BulkWritableCableRequestStatus {
	if o == nil || IsNil(o.SupportedDataRates) {
		var ret []BulkWritableCableRequestStatus
		return ret
	}
	return o.SupportedDataRates
}

// GetSupportedDataRatesOk returns a tuple with the SupportedDataRates field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetSupportedDataRatesOk() ([]BulkWritableCableRequestStatus, bool) {
	if o == nil || IsNil(o.SupportedDataRates) {
		return nil, false
	}
	return o.SupportedDataRates, true
}

// HasSupportedDataRates returns a boolean if a field has been set.
func (o *RadioProfile) HasSupportedDataRates() bool {
	if o != nil && !IsNil(o.SupportedDataRates) {
		return true
	}

	return false
}

// SetSupportedDataRates gets a reference to the given []BulkWritableCableRequestStatus and assigns it to the SupportedDataRates field.
func (o *RadioProfile) SetSupportedDataRates(v []BulkWritableCableRequestStatus) {
	o.SupportedDataRates = v
}

// GetCreated returns the Created field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *RadioProfile) GetCreated() time.Time {
	if o == nil || o.Created.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.Created.Get()
}

// GetCreatedOk returns a tuple with the Created field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RadioProfile) GetCreatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.Created.Get(), o.Created.IsSet()
}

// SetCreated sets field value
func (o *RadioProfile) SetCreated(v time.Time) {
	o.Created.Set(&v)
}

// GetLastUpdated returns the LastUpdated field value
// If the value is explicit nil, the zero value for time.Time will be returned
func (o *RadioProfile) GetLastUpdated() time.Time {
	if o == nil || o.LastUpdated.Get() == nil {
		var ret time.Time
		return ret
	}

	return *o.LastUpdated.Get()
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *RadioProfile) GetLastUpdatedOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return o.LastUpdated.Get(), o.LastUpdated.IsSet()
}

// SetLastUpdated sets field value
func (o *RadioProfile) SetLastUpdated(v time.Time) {
	o.LastUpdated.Set(&v)
}

// GetNotesUrl returns the NotesUrl field value
func (o *RadioProfile) GetNotesUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NotesUrl
}

// GetNotesUrlOk returns a tuple with the NotesUrl field value
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetNotesUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NotesUrl, true
}

// SetNotesUrl sets field value
func (o *RadioProfile) SetNotesUrl(v string) {
	o.NotesUrl = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *RadioProfile) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *RadioProfile) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *RadioProfile) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *RadioProfile) GetTags() []BulkWritableCableRequestStatus {
	if o == nil || IsNil(o.Tags) {
		var ret []BulkWritableCableRequestStatus
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RadioProfile) GetTagsOk() ([]BulkWritableCableRequestStatus, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *RadioProfile) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []BulkWritableCableRequestStatus and assigns it to the Tags field.
func (o *RadioProfile) SetTags(v []BulkWritableCableRequestStatus) {
	o.Tags = v
}

func (o RadioProfile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RadioProfile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["object_type"] = o.ObjectType
	toSerialize["display"] = o.Display
	toSerialize["url"] = o.Url
	toSerialize["natural_slug"] = o.NaturalSlug
	if !IsNil(o.ChannelWidth) {
		toSerialize["channel_width"] = o.ChannelWidth
	}
	if !IsNil(o.AllowedChannelList) {
		toSerialize["allowed_channel_list"] = o.AllowedChannelList
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Frequency) {
		toSerialize["frequency"] = o.Frequency
	}
	if o.TxPowerMin.IsSet() {
		toSerialize["tx_power_min"] = o.TxPowerMin.Get()
	}
	if o.TxPowerMax.IsSet() {
		toSerialize["tx_power_max"] = o.TxPowerMax.Get()
	}
	toSerialize["regulatory_domain"] = o.RegulatoryDomain
	if o.RxPowerMin.IsSet() {
		toSerialize["rx_power_min"] = o.RxPowerMin.Get()
	}
	if !IsNil(o.SupportedDataRates) {
		toSerialize["supported_data_rates"] = o.SupportedDataRates
	}
	toSerialize["created"] = o.Created.Get()
	toSerialize["last_updated"] = o.LastUpdated.Get()
	toSerialize["notes_url"] = o.NotesUrl
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *RadioProfile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"object_type",
		"display",
		"url",
		"natural_slug",
		"name",
		"regulatory_domain",
		"created",
		"last_updated",
		"notes_url",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varRadioProfile := _RadioProfile{}

	err = json.Unmarshal(data, &varRadioProfile)

	if err != nil {
		return err
	}

	*o = RadioProfile(varRadioProfile)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "object_type")
		delete(additionalProperties, "display")
		delete(additionalProperties, "url")
		delete(additionalProperties, "natural_slug")
		delete(additionalProperties, "channel_width")
		delete(additionalProperties, "allowed_channel_list")
		delete(additionalProperties, "name")
		delete(additionalProperties, "frequency")
		delete(additionalProperties, "tx_power_min")
		delete(additionalProperties, "tx_power_max")
		delete(additionalProperties, "regulatory_domain")
		delete(additionalProperties, "rx_power_min")
		delete(additionalProperties, "supported_data_rates")
		delete(additionalProperties, "created")
		delete(additionalProperties, "last_updated")
		delete(additionalProperties, "notes_url")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "tags")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableRadioProfile struct {
	value *RadioProfile
	isSet bool
}

func (v NullableRadioProfile) Get() *RadioProfile {
	return v.value
}

func (v *NullableRadioProfile) Set(val *RadioProfile) {
	v.value = val
	v.isSet = true
}

func (v NullableRadioProfile) IsSet() bool {
	return v.isSet
}

func (v *NullableRadioProfile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRadioProfile(val *RadioProfile) *NullableRadioProfile {
	return &NullableRadioProfile{value: val, isSet: true}
}

func (v NullableRadioProfile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRadioProfile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


