/*
API Documentation

Source of truth and network automation platform

API version: 2.3.2 (2.3)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// checks if the BulkWritableContactAssociationRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkWritableContactAssociationRequest{}

// BulkWritableContactAssociationRequest Base class to use for serializers based on OrganizationalModel or PrimaryModel.  Can also be used for models derived from BaseModel, so long as they support custom fields, notes, and relationships.
type BulkWritableContactAssociationRequest struct {
	Id string `json:"id"`
	AssociatedObjectType string `json:"associated_object_type"`
	AssociatedObjectId string `json:"associated_object_id"`
	Contact NullableBulkWritableCircuitRequestTenant `json:"contact,omitempty"`
	Team NullableBulkWritableCircuitRequestTenant `json:"team,omitempty"`
	Role BulkWritableCableRequestStatus `json:"role"`
	Status BulkWritableCableRequestStatus `json:"status"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Relationships *map[string]BulkWritableCableRequestRelationshipsValue `json:"relationships,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _BulkWritableContactAssociationRequest BulkWritableContactAssociationRequest

// NewBulkWritableContactAssociationRequest instantiates a new BulkWritableContactAssociationRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkWritableContactAssociationRequest(id string, associatedObjectType string, associatedObjectId string, role BulkWritableCableRequestStatus, status BulkWritableCableRequestStatus) *BulkWritableContactAssociationRequest {
	this := BulkWritableContactAssociationRequest{}
	this.Id = id
	this.AssociatedObjectType = associatedObjectType
	this.AssociatedObjectId = associatedObjectId
	this.Role = role
	this.Status = status
	return &this
}

// NewBulkWritableContactAssociationRequestWithDefaults instantiates a new BulkWritableContactAssociationRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkWritableContactAssociationRequestWithDefaults() *BulkWritableContactAssociationRequest {
	this := BulkWritableContactAssociationRequest{}
	return &this
}

// GetId returns the Id field value
func (o *BulkWritableContactAssociationRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BulkWritableContactAssociationRequest) SetId(v string) {
	o.Id = v
}

// GetAssociatedObjectType returns the AssociatedObjectType field value
func (o *BulkWritableContactAssociationRequest) GetAssociatedObjectType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssociatedObjectType
}

// GetAssociatedObjectTypeOk returns a tuple with the AssociatedObjectType field value
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetAssociatedObjectTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssociatedObjectType, true
}

// SetAssociatedObjectType sets field value
func (o *BulkWritableContactAssociationRequest) SetAssociatedObjectType(v string) {
	o.AssociatedObjectType = v
}

// GetAssociatedObjectId returns the AssociatedObjectId field value
func (o *BulkWritableContactAssociationRequest) GetAssociatedObjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssociatedObjectId
}

// GetAssociatedObjectIdOk returns a tuple with the AssociatedObjectId field value
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetAssociatedObjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssociatedObjectId, true
}

// SetAssociatedObjectId sets field value
func (o *BulkWritableContactAssociationRequest) SetAssociatedObjectId(v string) {
	o.AssociatedObjectId = v
}

// GetContact returns the Contact field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkWritableContactAssociationRequest) GetContact() BulkWritableCircuitRequestTenant {
	if o == nil || IsNil(o.Contact.Get()) {
		var ret BulkWritableCircuitRequestTenant
		return ret
	}
	return *o.Contact.Get()
}

// GetContactOk returns a tuple with the Contact field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkWritableContactAssociationRequest) GetContactOk() (*BulkWritableCircuitRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Contact.Get(), o.Contact.IsSet()
}

// HasContact returns a boolean if a field has been set.
func (o *BulkWritableContactAssociationRequest) HasContact() bool {
	if o != nil && o.Contact.IsSet() {
		return true
	}

	return false
}

// SetContact gets a reference to the given NullableBulkWritableCircuitRequestTenant and assigns it to the Contact field.
func (o *BulkWritableContactAssociationRequest) SetContact(v BulkWritableCircuitRequestTenant) {
	o.Contact.Set(&v)
}
// SetContactNil sets the value for Contact to be an explicit nil
func (o *BulkWritableContactAssociationRequest) SetContactNil() {
	o.Contact.Set(nil)
}

// UnsetContact ensures that no value is present for Contact, not even an explicit nil
func (o *BulkWritableContactAssociationRequest) UnsetContact() {
	o.Contact.Unset()
}

// GetTeam returns the Team field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *BulkWritableContactAssociationRequest) GetTeam() BulkWritableCircuitRequestTenant {
	if o == nil || IsNil(o.Team.Get()) {
		var ret BulkWritableCircuitRequestTenant
		return ret
	}
	return *o.Team.Get()
}

// GetTeamOk returns a tuple with the Team field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *BulkWritableContactAssociationRequest) GetTeamOk() (*BulkWritableCircuitRequestTenant, bool) {
	if o == nil {
		return nil, false
	}
	return o.Team.Get(), o.Team.IsSet()
}

// HasTeam returns a boolean if a field has been set.
func (o *BulkWritableContactAssociationRequest) HasTeam() bool {
	if o != nil && o.Team.IsSet() {
		return true
	}

	return false
}

// SetTeam gets a reference to the given NullableBulkWritableCircuitRequestTenant and assigns it to the Team field.
func (o *BulkWritableContactAssociationRequest) SetTeam(v BulkWritableCircuitRequestTenant) {
	o.Team.Set(&v)
}
// SetTeamNil sets the value for Team to be an explicit nil
func (o *BulkWritableContactAssociationRequest) SetTeamNil() {
	o.Team.Set(nil)
}

// UnsetTeam ensures that no value is present for Team, not even an explicit nil
func (o *BulkWritableContactAssociationRequest) UnsetTeam() {
	o.Team.Unset()
}

// GetRole returns the Role field value
func (o *BulkWritableContactAssociationRequest) GetRole() BulkWritableCableRequestStatus {
	if o == nil {
		var ret BulkWritableCableRequestStatus
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetRoleOk() (*BulkWritableCableRequestStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *BulkWritableContactAssociationRequest) SetRole(v BulkWritableCableRequestStatus) {
	o.Role = v
}

// GetStatus returns the Status field value
func (o *BulkWritableContactAssociationRequest) GetStatus() BulkWritableCableRequestStatus {
	if o == nil {
		var ret BulkWritableCableRequestStatus
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetStatusOk() (*BulkWritableCableRequestStatus, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *BulkWritableContactAssociationRequest) SetStatus(v BulkWritableCableRequestStatus) {
	o.Status = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *BulkWritableContactAssociationRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *BulkWritableContactAssociationRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *BulkWritableContactAssociationRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *BulkWritableContactAssociationRequest) GetRelationships() map[string]BulkWritableCableRequestRelationshipsValue {
	if o == nil || IsNil(o.Relationships) {
		var ret map[string]BulkWritableCableRequestRelationshipsValue
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BulkWritableContactAssociationRequest) GetRelationshipsOk() (*map[string]BulkWritableCableRequestRelationshipsValue, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *BulkWritableContactAssociationRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given map[string]BulkWritableCableRequestRelationshipsValue and assigns it to the Relationships field.
func (o *BulkWritableContactAssociationRequest) SetRelationships(v map[string]BulkWritableCableRequestRelationshipsValue) {
	o.Relationships = &v
}

func (o BulkWritableContactAssociationRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkWritableContactAssociationRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["associated_object_type"] = o.AssociatedObjectType
	toSerialize["associated_object_id"] = o.AssociatedObjectId
	if o.Contact.IsSet() {
		toSerialize["contact"] = o.Contact.Get()
	}
	if o.Team.IsSet() {
		toSerialize["team"] = o.Team.Get()
	}
	toSerialize["role"] = o.Role
	toSerialize["status"] = o.Status
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *BulkWritableContactAssociationRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"associated_object_type",
		"associated_object_id",
		"role",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkWritableContactAssociationRequest := _BulkWritableContactAssociationRequest{}

	err = json.Unmarshal(data, &varBulkWritableContactAssociationRequest)

	if err != nil {
		return err
	}

	*o = BulkWritableContactAssociationRequest(varBulkWritableContactAssociationRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "associated_object_type")
		delete(additionalProperties, "associated_object_id")
		delete(additionalProperties, "contact")
		delete(additionalProperties, "team")
		delete(additionalProperties, "role")
		delete(additionalProperties, "status")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "relationships")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableBulkWritableContactAssociationRequest struct {
	value *BulkWritableContactAssociationRequest
	isSet bool
}

func (v NullableBulkWritableContactAssociationRequest) Get() *BulkWritableContactAssociationRequest {
	return v.value
}

func (v *NullableBulkWritableContactAssociationRequest) Set(val *BulkWritableContactAssociationRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkWritableContactAssociationRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkWritableContactAssociationRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkWritableContactAssociationRequest(val *BulkWritableContactAssociationRequest) *NullableBulkWritableContactAssociationRequest {
	return &NullableBulkWritableContactAssociationRequest{value: val, isSet: true}
}

func (v NullableBulkWritableContactAssociationRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkWritableContactAssociationRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


