/*
API Documentation

Source of truth and network automation platform

API version: 3.0.11 (3.0)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
	"fmt"
)

// checks if the PatchedBulkWritableUniqueValidationRuleRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedBulkWritableUniqueValidationRuleRequest{}

// PatchedBulkWritableUniqueValidationRuleRequest Serializer for `UniqueValidationRule` objects.
type PatchedBulkWritableUniqueValidationRuleRequest struct {
	Id string `json:"id"`
	ContentType *string `json:"content_type,omitempty"`
	Name *string `json:"name,omitempty"`
	Field *string `json:"field,omitempty"`
	Enabled *bool `json:"enabled,omitempty"`
	// Optional error message to display when validation fails.
	ErrorMessage *string `json:"error_message,omitempty"`
	MaxInstances *int32 `json:"max_instances,omitempty"`
	Tags []ApprovalWorkflowStageResponseApprovalWorkflowStage `json:"tags,omitempty"`
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Relationships *map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue `json:"relationships,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedBulkWritableUniqueValidationRuleRequest PatchedBulkWritableUniqueValidationRuleRequest

// NewPatchedBulkWritableUniqueValidationRuleRequest instantiates a new PatchedBulkWritableUniqueValidationRuleRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedBulkWritableUniqueValidationRuleRequest(id string) *PatchedBulkWritableUniqueValidationRuleRequest {
	this := PatchedBulkWritableUniqueValidationRuleRequest{}
	this.Id = id
	return &this
}

// NewPatchedBulkWritableUniqueValidationRuleRequestWithDefaults instantiates a new PatchedBulkWritableUniqueValidationRuleRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedBulkWritableUniqueValidationRuleRequestWithDefaults() *PatchedBulkWritableUniqueValidationRuleRequest {
	this := PatchedBulkWritableUniqueValidationRuleRequest{}
	return &this
}

// GetId returns the Id field value
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetId(v string) {
	o.Id = v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetContentType() string {
	if o == nil || IsNil(o.ContentType) {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetContentTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ContentType) {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasContentType() bool {
	if o != nil && !IsNil(o.ContentType) {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetContentType(v string) {
	o.ContentType = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetName(v string) {
	o.Name = &v
}

// GetField returns the Field field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetField() string {
	if o == nil || IsNil(o.Field) {
		var ret string
		return ret
	}
	return *o.Field
}

// GetFieldOk returns a tuple with the Field field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetFieldOk() (*string, bool) {
	if o == nil || IsNil(o.Field) {
		return nil, false
	}
	return o.Field, true
}

// HasField returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasField() bool {
	if o != nil && !IsNil(o.Field) {
		return true
	}

	return false
}

// SetField gets a reference to the given string and assigns it to the Field field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetField(v string) {
	o.Field = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetEnabled() bool {
	if o == nil || IsNil(o.Enabled) {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.Enabled) {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasEnabled() bool {
	if o != nil && !IsNil(o.Enabled) {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetErrorMessage returns the ErrorMessage field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetErrorMessage() string {
	if o == nil || IsNil(o.ErrorMessage) {
		var ret string
		return ret
	}
	return *o.ErrorMessage
}

// GetErrorMessageOk returns a tuple with the ErrorMessage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetErrorMessageOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorMessage) {
		return nil, false
	}
	return o.ErrorMessage, true
}

// HasErrorMessage returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasErrorMessage() bool {
	if o != nil && !IsNil(o.ErrorMessage) {
		return true
	}

	return false
}

// SetErrorMessage gets a reference to the given string and assigns it to the ErrorMessage field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetErrorMessage(v string) {
	o.ErrorMessage = &v
}

// GetMaxInstances returns the MaxInstances field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetMaxInstances() int32 {
	if o == nil || IsNil(o.MaxInstances) {
		var ret int32
		return ret
	}
	return *o.MaxInstances
}

// GetMaxInstancesOk returns a tuple with the MaxInstances field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetMaxInstancesOk() (*int32, bool) {
	if o == nil || IsNil(o.MaxInstances) {
		return nil, false
	}
	return o.MaxInstances, true
}

// HasMaxInstances returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasMaxInstances() bool {
	if o != nil && !IsNil(o.MaxInstances) {
		return true
	}

	return false
}

// SetMaxInstances gets a reference to the given int32 and assigns it to the MaxInstances field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetMaxInstances(v int32) {
	o.MaxInstances = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetTags() []ApprovalWorkflowStageResponseApprovalWorkflowStage {
	if o == nil || IsNil(o.Tags) {
		var ret []ApprovalWorkflowStageResponseApprovalWorkflowStage
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetTagsOk() ([]ApprovalWorkflowStageResponseApprovalWorkflowStage, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []ApprovalWorkflowStageResponseApprovalWorkflowStage and assigns it to the Tags field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetTags(v []ApprovalWorkflowStageResponseApprovalWorkflowStage) {
	o.Tags = v
}

// GetCustomFields returns the CustomFields field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetCustomFields() map[string]interface{} {
	if o == nil || IsNil(o.CustomFields) {
		var ret map[string]interface{}
		return ret
	}
	return o.CustomFields
}

// GetCustomFieldsOk returns a tuple with the CustomFields field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetCustomFieldsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.CustomFields) {
		return map[string]interface{}{}, false
	}
	return o.CustomFields, true
}

// HasCustomFields returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasCustomFields() bool {
	if o != nil && !IsNil(o.CustomFields) {
		return true
	}

	return false
}

// SetCustomFields gets a reference to the given map[string]interface{} and assigns it to the CustomFields field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetCustomFields(v map[string]interface{}) {
	o.CustomFields = v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetRelationships() map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue {
	if o == nil || IsNil(o.Relationships) {
		var ret map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) GetRelationshipsOk() (*map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue and assigns it to the Relationships field.
func (o *PatchedBulkWritableUniqueValidationRuleRequest) SetRelationships(v map[string]ApprovalWorkflowDefinitionRequestRelationshipsValue) {
	o.Relationships = &v
}

func (o PatchedBulkWritableUniqueValidationRuleRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedBulkWritableUniqueValidationRuleRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.ContentType) {
		toSerialize["content_type"] = o.ContentType
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Field) {
		toSerialize["field"] = o.Field
	}
	if !IsNil(o.Enabled) {
		toSerialize["enabled"] = o.Enabled
	}
	if !IsNil(o.ErrorMessage) {
		toSerialize["error_message"] = o.ErrorMessage
	}
	if !IsNil(o.MaxInstances) {
		toSerialize["max_instances"] = o.MaxInstances
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.CustomFields) {
		toSerialize["custom_fields"] = o.CustomFields
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedBulkWritableUniqueValidationRuleRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPatchedBulkWritableUniqueValidationRuleRequest := _PatchedBulkWritableUniqueValidationRuleRequest{}

	err = json.Unmarshal(data, &varPatchedBulkWritableUniqueValidationRuleRequest)

	if err != nil {
		return err
	}

	*o = PatchedBulkWritableUniqueValidationRuleRequest(varPatchedBulkWritableUniqueValidationRuleRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "content_type")
		delete(additionalProperties, "name")
		delete(additionalProperties, "field")
		delete(additionalProperties, "enabled")
		delete(additionalProperties, "error_message")
		delete(additionalProperties, "max_instances")
		delete(additionalProperties, "tags")
		delete(additionalProperties, "custom_fields")
		delete(additionalProperties, "relationships")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedBulkWritableUniqueValidationRuleRequest struct {
	value *PatchedBulkWritableUniqueValidationRuleRequest
	isSet bool
}

func (v NullablePatchedBulkWritableUniqueValidationRuleRequest) Get() *PatchedBulkWritableUniqueValidationRuleRequest {
	return v.value
}

func (v *NullablePatchedBulkWritableUniqueValidationRuleRequest) Set(val *PatchedBulkWritableUniqueValidationRuleRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedBulkWritableUniqueValidationRuleRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedBulkWritableUniqueValidationRuleRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedBulkWritableUniqueValidationRuleRequest(val *PatchedBulkWritableUniqueValidationRuleRequest) *NullablePatchedBulkWritableUniqueValidationRuleRequest {
	return &NullablePatchedBulkWritableUniqueValidationRuleRequest{value: val, isSet: true}
}

func (v NullablePatchedBulkWritableUniqueValidationRuleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedBulkWritableUniqueValidationRuleRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


