/*
API Documentation

Source of truth and network automation platform

API version: 3.1.8 (3.1)
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package nautobot

import (
	"encoding/json"
)

// checks if the PatchedVRFDeviceAssignmentRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PatchedVRFDeviceAssignmentRequest{}

// PatchedVRFDeviceAssignmentRequest Extends the built-in ModelSerializer to enforce calling full_clean() on a copy of the associated instance during validation. (DRF does not do this by default; see https://github.com/encode/django-rest-framework/issues/3144)
type PatchedVRFDeviceAssignmentRequest struct {
	Id *string `json:"id,omitempty"`
	// Unique route distinguisher (as defined in RFC 4364)
	Rd NullableString `json:"rd,omitempty"`
	Name *string `json:"name,omitempty"`
	Vrf *BulkWritableCableRequestStatus `json:"vrf,omitempty"`
	Device NullableApprovalWorkflowUser `json:"device,omitempty"`
	VirtualMachine NullableApprovalWorkflowUser `json:"virtual_machine,omitempty"`
	VirtualDeviceContext NullableApprovalWorkflowUser `json:"virtual_device_context,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _PatchedVRFDeviceAssignmentRequest PatchedVRFDeviceAssignmentRequest

// NewPatchedVRFDeviceAssignmentRequest instantiates a new PatchedVRFDeviceAssignmentRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPatchedVRFDeviceAssignmentRequest() *PatchedVRFDeviceAssignmentRequest {
	this := PatchedVRFDeviceAssignmentRequest{}
	return &this
}

// NewPatchedVRFDeviceAssignmentRequestWithDefaults instantiates a new PatchedVRFDeviceAssignmentRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPatchedVRFDeviceAssignmentRequestWithDefaults() *PatchedVRFDeviceAssignmentRequest {
	this := PatchedVRFDeviceAssignmentRequest{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *PatchedVRFDeviceAssignmentRequest) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedVRFDeviceAssignmentRequest) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *PatchedVRFDeviceAssignmentRequest) SetId(v string) {
	o.Id = &v
}

// GetRd returns the Rd field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVRFDeviceAssignmentRequest) GetRd() string {
	if o == nil || IsNil(o.Rd.Get()) {
		var ret string
		return ret
	}
	return *o.Rd.Get()
}

// GetRdOk returns a tuple with the Rd field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVRFDeviceAssignmentRequest) GetRdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rd.Get(), o.Rd.IsSet()
}

// HasRd returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasRd() bool {
	if o != nil && o.Rd.IsSet() {
		return true
	}

	return false
}

// SetRd gets a reference to the given NullableString and assigns it to the Rd field.
func (o *PatchedVRFDeviceAssignmentRequest) SetRd(v string) {
	o.Rd.Set(&v)
}
// SetRdNil sets the value for Rd to be an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) SetRdNil() {
	o.Rd.Set(nil)
}

// UnsetRd ensures that no value is present for Rd, not even an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) UnsetRd() {
	o.Rd.Unset()
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *PatchedVRFDeviceAssignmentRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedVRFDeviceAssignmentRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *PatchedVRFDeviceAssignmentRequest) SetName(v string) {
	o.Name = &v
}

// GetVrf returns the Vrf field value if set, zero value otherwise.
func (o *PatchedVRFDeviceAssignmentRequest) GetVrf() BulkWritableCableRequestStatus {
	if o == nil || IsNil(o.Vrf) {
		var ret BulkWritableCableRequestStatus
		return ret
	}
	return *o.Vrf
}

// GetVrfOk returns a tuple with the Vrf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PatchedVRFDeviceAssignmentRequest) GetVrfOk() (*BulkWritableCableRequestStatus, bool) {
	if o == nil || IsNil(o.Vrf) {
		return nil, false
	}
	return o.Vrf, true
}

// HasVrf returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasVrf() bool {
	if o != nil && !IsNil(o.Vrf) {
		return true
	}

	return false
}

// SetVrf gets a reference to the given BulkWritableCableRequestStatus and assigns it to the Vrf field.
func (o *PatchedVRFDeviceAssignmentRequest) SetVrf(v BulkWritableCableRequestStatus) {
	o.Vrf = &v
}

// GetDevice returns the Device field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVRFDeviceAssignmentRequest) GetDevice() ApprovalWorkflowUser {
	if o == nil || IsNil(o.Device.Get()) {
		var ret ApprovalWorkflowUser
		return ret
	}
	return *o.Device.Get()
}

// GetDeviceOk returns a tuple with the Device field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVRFDeviceAssignmentRequest) GetDeviceOk() (*ApprovalWorkflowUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.Device.Get(), o.Device.IsSet()
}

// HasDevice returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasDevice() bool {
	if o != nil && o.Device.IsSet() {
		return true
	}

	return false
}

// SetDevice gets a reference to the given NullableApprovalWorkflowUser and assigns it to the Device field.
func (o *PatchedVRFDeviceAssignmentRequest) SetDevice(v ApprovalWorkflowUser) {
	o.Device.Set(&v)
}
// SetDeviceNil sets the value for Device to be an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) SetDeviceNil() {
	o.Device.Set(nil)
}

// UnsetDevice ensures that no value is present for Device, not even an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) UnsetDevice() {
	o.Device.Unset()
}

// GetVirtualMachine returns the VirtualMachine field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVRFDeviceAssignmentRequest) GetVirtualMachine() ApprovalWorkflowUser {
	if o == nil || IsNil(o.VirtualMachine.Get()) {
		var ret ApprovalWorkflowUser
		return ret
	}
	return *o.VirtualMachine.Get()
}

// GetVirtualMachineOk returns a tuple with the VirtualMachine field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVRFDeviceAssignmentRequest) GetVirtualMachineOk() (*ApprovalWorkflowUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualMachine.Get(), o.VirtualMachine.IsSet()
}

// HasVirtualMachine returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasVirtualMachine() bool {
	if o != nil && o.VirtualMachine.IsSet() {
		return true
	}

	return false
}

// SetVirtualMachine gets a reference to the given NullableApprovalWorkflowUser and assigns it to the VirtualMachine field.
func (o *PatchedVRFDeviceAssignmentRequest) SetVirtualMachine(v ApprovalWorkflowUser) {
	o.VirtualMachine.Set(&v)
}
// SetVirtualMachineNil sets the value for VirtualMachine to be an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) SetVirtualMachineNil() {
	o.VirtualMachine.Set(nil)
}

// UnsetVirtualMachine ensures that no value is present for VirtualMachine, not even an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) UnsetVirtualMachine() {
	o.VirtualMachine.Unset()
}

// GetVirtualDeviceContext returns the VirtualDeviceContext field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PatchedVRFDeviceAssignmentRequest) GetVirtualDeviceContext() ApprovalWorkflowUser {
	if o == nil || IsNil(o.VirtualDeviceContext.Get()) {
		var ret ApprovalWorkflowUser
		return ret
	}
	return *o.VirtualDeviceContext.Get()
}

// GetVirtualDeviceContextOk returns a tuple with the VirtualDeviceContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PatchedVRFDeviceAssignmentRequest) GetVirtualDeviceContextOk() (*ApprovalWorkflowUser, bool) {
	if o == nil {
		return nil, false
	}
	return o.VirtualDeviceContext.Get(), o.VirtualDeviceContext.IsSet()
}

// HasVirtualDeviceContext returns a boolean if a field has been set.
func (o *PatchedVRFDeviceAssignmentRequest) HasVirtualDeviceContext() bool {
	if o != nil && o.VirtualDeviceContext.IsSet() {
		return true
	}

	return false
}

// SetVirtualDeviceContext gets a reference to the given NullableApprovalWorkflowUser and assigns it to the VirtualDeviceContext field.
func (o *PatchedVRFDeviceAssignmentRequest) SetVirtualDeviceContext(v ApprovalWorkflowUser) {
	o.VirtualDeviceContext.Set(&v)
}
// SetVirtualDeviceContextNil sets the value for VirtualDeviceContext to be an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) SetVirtualDeviceContextNil() {
	o.VirtualDeviceContext.Set(nil)
}

// UnsetVirtualDeviceContext ensures that no value is present for VirtualDeviceContext, not even an explicit nil
func (o *PatchedVRFDeviceAssignmentRequest) UnsetVirtualDeviceContext() {
	o.VirtualDeviceContext.Unset()
}

func (o PatchedVRFDeviceAssignmentRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PatchedVRFDeviceAssignmentRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if o.Rd.IsSet() {
		toSerialize["rd"] = o.Rd.Get()
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Vrf) {
		toSerialize["vrf"] = o.Vrf
	}
	if o.Device.IsSet() {
		toSerialize["device"] = o.Device.Get()
	}
	if o.VirtualMachine.IsSet() {
		toSerialize["virtual_machine"] = o.VirtualMachine.Get()
	}
	if o.VirtualDeviceContext.IsSet() {
		toSerialize["virtual_device_context"] = o.VirtualDeviceContext.Get()
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *PatchedVRFDeviceAssignmentRequest) UnmarshalJSON(data []byte) (err error) {
	varPatchedVRFDeviceAssignmentRequest := _PatchedVRFDeviceAssignmentRequest{}

	err = json.Unmarshal(data, &varPatchedVRFDeviceAssignmentRequest)

	if err != nil {
		return err
	}

	*o = PatchedVRFDeviceAssignmentRequest(varPatchedVRFDeviceAssignmentRequest)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "rd")
		delete(additionalProperties, "name")
		delete(additionalProperties, "vrf")
		delete(additionalProperties, "device")
		delete(additionalProperties, "virtual_machine")
		delete(additionalProperties, "virtual_device_context")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullablePatchedVRFDeviceAssignmentRequest struct {
	value *PatchedVRFDeviceAssignmentRequest
	isSet bool
}

func (v NullablePatchedVRFDeviceAssignmentRequest) Get() *PatchedVRFDeviceAssignmentRequest {
	return v.value
}

func (v *NullablePatchedVRFDeviceAssignmentRequest) Set(val *PatchedVRFDeviceAssignmentRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePatchedVRFDeviceAssignmentRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePatchedVRFDeviceAssignmentRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePatchedVRFDeviceAssignmentRequest(val *PatchedVRFDeviceAssignmentRequest) *NullablePatchedVRFDeviceAssignmentRequest {
	return &NullablePatchedVRFDeviceAssignmentRequest{value: val, isSet: true}
}

func (v NullablePatchedVRFDeviceAssignmentRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePatchedVRFDeviceAssignmentRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


