services:
  oapi:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - NAUTOBOT_VER=${NAUTOBOT_VER}
    volumes:
      - "../../:/client"
    dns:
      - 1.1.1.1
      - 8.8.8.8
