---
name: "CI"
on: # yamllint disable-line rule:truthy rule:comments
  push:
    branches:
      - "main"
      - "develop"
    tags:
      - "v*"
  pull_request: ~
concurrency: # Cancel any existing runs of this workflow for this same PR
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Get go-nautobot code"
        uses: actions/checkout@v3
      - name: "Run tests"
        run: |
          cd development
          make
